/*! -- File: showMe.js ( Input 0 ) -- */
function showMe(T){var w;function ja(){var b=a.carousel.find(".active img"),c=function(){e.trigger(l.READY,d)};b[0].complete?c():b[0].onload=function(){requestAnimationFrame(function(){requestAnimationFrame(c)})}}function U(b){V(b);w=!0;(!x||1==d.getCurrentSection()&&1==d.getCurrentStep())&&a.introductionContainerPlayButton.text(this.showMe.STRINGS.PLAY);a.introductionContainerPlayButton.off("click").on("click",function(){d.goToOverallStep(d.getOverallStep());f();w=!1})}function ka(b){V(b);b=a.sectionInfo.data("number-of-sections");
d.getCurrentSection()+1>b&&a.introductionContainerPlayButton.text(this.showMe.STRINGS.OK);a.introductionContainerPlayButton.off("click").on("click",function(){var b=a.sectionInfo.data("number-of-sections"),g=d.getCurrentSection()+1;b>=g&&!a.sectionInfo.find("#section-"+(d.getCurrentSection()+1)).data("section-introduction")?(a.carousel.carousel("next"),b=d.getCurrentSection(),a.sectionInfo.find("#section-"+b),t(),d.toggleActiveStep(),I(),f()):(d.nextStep(),I())})}function V(b){if(b){W();m=!1;a.introductionContainerPlayButton.prop("disabled",
!1);a.introductionText.html(b);a.introductionContainerPlayButton.text(this.showMe.STRINGS.CONTINUE);b=a.introductionText.height();var c=a.introductionTextContainer.height();b>c?(a.introductionTextContainer.addClass("introduction-text-flex-start"),a.introductionTextContainer.scrollTop(0)):a.introductionTextContainer.removeClass("introduction-text-flex-start");a.introductionOverlay.addClass("justify-content-center");a.introductionOverlay.removeClass("hide-introduction");a.playButton.off("click").on("click",
function(){a.introductionContainerPlayButton.trigger("click")})}}function J(){a.introductionOverlay.addClass("hide-introduction");a.playButton.off("click").on("click",f);a.introductionOverlay.removeClass("justify-content-center")}function y(b){a.inner.animate({top:0,left:0,scale:1},{duration:b,start:K,step:L})}function M(){var b=a.sideContainer.find(".panel"),c=a.sideContainer.find(".active");b.animate({scrollTop:c.position().top-b.position().top+b.scrollTop()});b=a.showMeContainer.find("#nextStep");
c=a.showMeContainer.find("#prevStep");a.inner.find(".item:first").hasClass("active")?c.prop("disabled",!0):c.prop("disabled",!1);a.inner.find(".item:last").hasClass("active")?b.prop("disabled",!0):b.prop("disabled",!1)}function z(){a.sideContainer.find(".panel").css("max-height",a.showMeContainer.height()+"px");var b=a.showMeContainer.find("#toggleZoom");1<=A()?b.hide():b.show()}function I(){var b=a.sideContainer.find(".active").children(".label"),c=b.data("time-start"),b=b.parent().data("section-count"),
d=0;for(i=1;i<b;i++){var h=a.sectionInfo.find("#section-"+i).data("section-duration");null!=h&&(d+=parseInt(h))}p=c=parseInt(c,10)+d;B(c);q()}function B(b,c){c?a.playBar.animate({width:b/C*100+"%"},c,"linear"):a.playBar.css("width",b/C*100+"%");q()}function la(){J();B(p,1E3);q();N=setInterval(function(){p+=1E3;B(p,1E3)},1E3)}function O(){a.playBar.stop();clearInterval(N)}function X(a){var c=(new Date(parseInt(a,10))).toISOString();return 36E5>a?c.slice(14,-5):c.slice(11,-5)}function q(){a.showMeContainer.find(".player-time").text(X(p)+
" / "+X(C))}function ma(a,c){Y?fetch(a).then(function(a){a.blob().then(function(a){var b=new FileReader;b.addEventListener("loadend",function(){Z(b.result.toString())});b.readAsDataURL(a)})}):Z(a)}function Z(b){a.mouse.hide();if(null!=b){var c={};c.mp3=b;a.jplayer.jPlayer({ready:function(){na(c)},supplied:"mp3",solution:"html",size:{height:"0px"}})}}function na(b){b&&a.jplayer.jPlayer("setMedia",b);a.playHeadButton.on("click",f);a.playButton.on("click",f);a.carousel.on("click",f);a.playButtonIcon.attr("class",
"fa fa-fw fa-play fa-2x");a.showMeContainer.find("#mute").click(function(){P?(P=!1,a.jplayer.jPlayer("unmute"),$(this).children("i").attr("class","fa fa-2x fa-fw fa-volume-up")):(P=!0,a.jplayer.jPlayer("mute"),$(this).children("i").attr("class","fa fa-2x fa-fw fa-volume-off"))});w||d.goToStep(1,1)}function E(){a.jplayer.jPlayer("pause")}function Q(b){var c=a.carousel.find(".active"),c=$(c).data("click-count"),c=parseInt(c);F=1<c?Math.min(800+399*Math.min(c,3),b):Math.min(1200,b);u=setTimeout(function(){u=
setTimeout(function(){var a=d.getCurrentSectionInfo(),b=d.getCurrentStep();if(a.data("section-size")==b&&(a=a.data("section-summary"))){ka(a);return}d.nextStep()},Math.min(F,b));aa(F)},Math.max(b-F,0))}function ba(a){return"#"+a.substring(a.indexOf("x")+1)}function t(){return parseInt(a.carousel.find(".active").data("interval"))}function A(){var b=d.getOverallStep?d.getOverallStep()-1:0;return captureProjectUtils.getScale(a,ca,b)}function oa(){var b=A();a.mouse.css("transform","scale("+b+") translate3d(0, 0, 0)");
a.dragOverlay.css("transform","scale("+b+") translate3d("+-a.dragOverlay.width()/2+"px , "+-a.dragOverlay.height()/2+"px , 0)")}function R(){this.carouselItem=a.carousel.find(".active");this.index=this.carouselItem.index()+1;this.totalItems=e.find(".item").length;this.currentItem=e.find(".item").get(this.index);this.minX=this.carouselItem.data("hotspotMinx");this.minY=this.carouselItem.data("hotspotMiny");this.width=this.carouselItem.data("hotspotWidth");this.height=this.carouselItem.data("hotspotHeight");
this.imageElement=a.carousel.find("img")[this.index-1];this.naturalWidth=this.imageElement.naturalWidth;this.naturalHeight=this.imageElement.naturalHeight;this.carouselWidth=this.carouselItem.width();this.carouselHeight=this.carouselItem.height();this.currentEvent=a.carousel.find(".active").data("eventType");this.scale=A();this.offset=0;this.activeElement=a.carousel.find(".active");this.clickCountAttr=$(this.activeElement).data("click-count");this.dataClicks=parseInt(this.clickCountAttr)}function pa(a,
c){var d=a-399*Math.min(c.dataClicks,3);c.currentEvent===k.SELECT&&(d=a/6);return d}function aa(b){var c=new R;if(c.index<c.totalItems){var d=function(){if(c.currentEvent===k.SELECT){var d=c.carouselItem.find("select").css("overflow","hidden"),g=d.find("option"),e=g.filter(".correct");d[0].size=g.length;a.mouse.animate({top:D+(e.position().top-c.height)*(1/c.scale)},b/4,function(){e.attr("selected",!0);setTimeout(function(){d[0].size=0;a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},
b/4)})}else if(c.currentEvent==k.DRAG_START||c.currentEvent==k.DRAG_FINISH&&G==k.DRAG_START||!b)c.currentEvent==k.DRAG_START||c.currentEvent==k.DRAG_FINISH&&G==k.DRAG_START||(a.mouse.find(".mouse-pointer").show(),a.mouse.find(".mouse-pointer-click").hide());else if(2==c.dataClicks|!c.dataClicks)for(g=c.dataClicks;0<g;)setTimeout(function(){a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},133),setTimeout(function(){a.mouse.find(".mouse-pointer").hide();a.mouse.find(".mouse-pointer-click").show()},
266),setTimeout(function(){a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},399),g--;else if(2<c.dataClicks|!c.dataClicks)for(g=c.dataClicks-1;0<g;)setTimeout(function(){a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},133*g),setTimeout(function(){a.mouse.find(".mouse-pointer").hide();a.mouse.find(".mouse-pointer-click").show()},266*g),setTimeout(function(){a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},
399*g),g--;else setTimeout(function(){a.mouse.find(".mouse-pointer").show();a.mouse.find(".mouse-pointer-click").hide()},399)};c.carouselWidth>c.naturalWidth&&(c.offset=(c.carouselWidth-c.naturalWidth)/2);var e=(parseInt(c.minX)+parseInt(c.width)/2)*c.scale+c.offset,D=(parseInt(c.minY)+parseInt(c.height)/2)*c.scale;0<c.width&&a.mouse.animate({left:e,top:D},pa(b,c),function(){a.mouse.find(".mouse-pointer").hide();a.mouse.find(".mouse-pointer-click").show();d();G=c.currentEvent});oa();v&&(1<=c.scale?
a.inner.animate({top:0,left:0,scale:1},{start:K,step:L,duration:b}):da());width=parseInt(c.width);height=parseInt(c.height);c.currentEvent==k.DRAG_START?(a.dragOverlay.width(c.width),a.dragOverlay.height(c.height),a.dragOverlay.css("top",D).css("left",e)):c.currentEvent==k.DRAG_FINISH&&G==k.DRAG_START&&(a.dragOverlay.show(),a.mouse.find(".mouse-pointer").hide(),a.mouse.find(".mouse-pointer-click").show(),a.dragOverlay.animate({left:e,top:D},parseInt(b),function(){a.dragOverlay.hide();a.mouse.find(".mouse-pointer").show();
a.mouse.find(".mouse-pointer-click").hide()}))}else y(400)}function H(){a.playHeadButton.parent().addClass("hidden")}function f(){if(m)W();else{x||(x=!0,d.goToStep(1,1));a.playButtonIcon.attr("class","fa fa-fw fa-pause fa-2x");H();a.jplayer.jPlayer("play");n&&!n[d.getOverallStep()-1]&&E();if(0!=r)Q(r),r=0;else{var b=t();Q(b)}la();a.mouse.show();e.trigger(l.PLAY,d)}m=!m}function W(){a.playButtonIcon.attr("class","fa fa-fw fa-play fa-2x");E();clearTimeout(u);a.jplayer.data("jPlayer");var b=p,c=t();
r=parseInt(a.carousel.find(".active").attr("data-start-time"),10)+parseInt(c,10)-b;O();e.trigger(l.PAUSE,d)}function qa(a){var c={};window.location.href.replace(location.hash,"").replace(/[?&]+([^=&]+)=?([^&]*)?/gi,function(a,b,d){c[b]=void 0!==d?d:""});return a?c[a]?c[a]:null:decodeURI(c)}var F=0,k={DRAG_START:"START_MOUSE_DRAGGED",DRAG_FINISH:"FINISH_MOUSE_DRAGGED",SELECT:"SELECT"},l={PLAY:"showMe.play",PAUSE:"showMe.pause",STEP_CHANGED:"showMe.stepChanged",ENDED:"showMe.ended",READY:"showMe.ready"};
showMe.STRINGS={PLAY:"Play",OK:"OK",CONTINUE:"Continue"};showMe.STRINGS=$.extend({},showMe.STRINGS,T.STRINGS);var u,G,m=!1,r=0,C,p=0,x=!1,v=!0,ca=!1,P=!1,ea=1,fa,S,ga,n,e,a,ha,N,Y=!0,ia={},d={};w=!1;(function(b){fa=b.sections;S=b.fileName;ga=b.m4aTag;n=b.audioSprite;v=b.panAndZoom;"undefined"!==typeof b.performAudioFetch&&(Y=b.performAudioFetch);"undefined"!==typeof b.uaSniffer&&(ia=b.uaSniffer);e=b.container;a={sectionInfo:e.find("#sectionInfo"),carousel:e.find("#softwareSimCarousel"),inner:e.find(".carousel-inner"),
sideContainer:e.find("#stepsSideContainer"),showMeContainer:e.find("#showMeContainer"),introductionOverlay:e.find("#introductionOverlay"),introductionTextContainer:e.find("#introductionTextContainer"),introductionText:e.find("#introductionText"),introductionContainerPlayButton:e.find("#introductionContainerPlayButton"),playHeadButton:e.find(".play-head-button"),playButtonIcon:e.find("#playButton .fa"),playButton:e.find("#playButton"),playBar:e.find(".bar"),mouse:e.find("#mouse"),dragOverlay:e.find("#showMeDragOverlay"),
jplayer:e.find("#jplayer")};a.inner.find(".item:first").addClass("active");a.sideContainer.find(".item:first").addClass("active");C=e.data("duration");S?ma(ga,S):(a.playHeadButton.on("click",f),a.playButton.on("click",f),a.carousel.on("click",f),a.showMeContainer.find("#mute").remove(),a.playButtonIcon.attr("class","fa fa-fw fa-play fa-2x"));$.each($("img.unloaded"),function(){$(this).attr("src",$(this).data("src"));$(this).removeClass("unloaded")});q();a.mouse.hide();a.dragOverlay.hide();a.sideContainer.on("click",
".step-item",function(){d.goToStep($(this).data("section-count"),$(this).data("step-count"));H()});a.showMeContainer.on("click","#hideSteps",function(){d.toggleSteps()});a.showMeContainer.on("click","#fullScreen",function(){d.toggleFullscreen()});a.showMeContainer.on("click","#nextStep",function(){var b=d.getCurrentSection(),c=d.getCurrentStep(),e=a.sectionInfo.find("#section-"+b).data("section-size");a.sectionInfo.data("number-of-sections");c+1>e?d.goToStep(b+1,1):d.goToStep(b,c+1);H()});a.showMeContainer.on("click",
"#prevStep",function(){var b=d.getCurrentSection(),c=d.getCurrentStep();a.sectionInfo.find("#section-"+b).data("section-size");a.sectionInfo.data("number-of-sections");if(1>c-1){for(var c=0,e=!1;!e;b--)c=a.sectionInfo.find("#section-"+(b-1)).data("section-size"),null!=c?e=!0:1==b&&(e=!0);d.goToStep(b,c)}else d.goToStep(b,c-1);H()});a.showMeContainer.on("click","#toggleZoom",function(){if(v){var b=$(this);a.inner.stop();v=!1;b.find(".fa").attr("class","fa fa-2x fa-fw fa-search-plus");b.prop("disabled",
!0);y(300);setTimeout(function(){a.mouse.css("transform","scale(1) translate3d(0, 0, 0)");a.dragOverlay.css("transform","scale(1) translate3d(-50%, -50%, 0)");b.prop("disabled",!1)},300)}else v=!0,da(),$(this).find(".fa").attr("class","fa fa-2x fa-fw fa-search-minus")});if(ia.safari){var c=function(a){a[0]&&a.addClass("blurFix")};c(a.carousel.find(".active img:not(.blurFix)"));a.carousel.on("slide.bs.carousel",function(a){c($(a.relatedTarget).find("img:not(.blurFix)"))})}z();ha=setInterval(z,1E3);
1==qa("hideSteps")&&(a.sideContainer.remove(),a.showMeContainer.css("width","100%"));y(0);e.on(l.STEP_CHANGED,function(){a.carousel.find(".item.active[data-event-type\x3d'STOP_CAPTURE']")[0]&&e.trigger(l.ENDED,d)});$(window).on("resize."+e.attr("id"),z);e.one(l.READY,function(){U(a.sectionInfo.find("#section-1").data("section-introduction"))});ja()})(T);d.destroy=function(){$(window).off("resize."+e.attr("id"));$.each(a,function(){$(this).off()});a=a.jplayer=null;clearInterval(ha);clearInterval(N);
clearTimeout(u)};d.getOverallStep=function(){var b=d.getCurrentStep(),c=d.getCurrentSection(),e;for(e=1;e<c;e++){var h=a.sectionInfo.find("#section-"+e).data("section-size");null!=h&&(b+=h)}return b};d.getCurrentStep=function(){return a.carousel.find(".active").data("stepCount")};d.getCurrentSection=function(){return a.carousel.find(".active").data("sectionCount")};d.getNumberOfSections=function(){return a.sectionInfo.data("number-of-sections")};d.toggleActiveStep=function(){a.showMeContainer.find(".item.active .targetHotspot").remove();
a.sideContainer.find(".active").attr("class","list-group-item step-item");a.sideContainer.find("[data-step-count\x3d'"+d.getCurrentStep()+"'][data-section-count\x3d'"+d.getCurrentSection()+"']").attr("class","list-group-item step-item active");currentActive=a.sideContainer.find(".active");a.sideContainer.find(".narration-text").addClass("hidden");currentActive.find(".narration-text").hasClass("hidden")&&currentActive.find(".narration-text").removeClass("hidden");a.sideContainer.find(".markerList").addClass("hidden");
currentActive.find(".markerList").hasClass("hidden")&&currentActive.find(".markerList").removeClass("hidden");var b=new R;if(b.currentEvent===k.SELECT){for(var c=fa[d.getCurrentSection()-1].steps[d.getCurrentStep()-1],e='\x3cdiv class\x3d"targetHotspot"\x3e\x3cselect\x3e',h=0;h<c.options.length;h++)e+="\x3coption value\x3d'"+c.options[h]+"'"+(c.initialSelection===c.options[h]?"selected":"")+' class\x3d"'+(c.options[h]===c.correct?"correct":"")+'"\x3e'+c.options[h]+"\x3c/option\x3e";e=$(e+"\x3c/select\x3e\x3c/div\x3e");
a.showMeContainer.find(".item.active").append(e);e.css({top:b.minY*b.scale,left:b.minX*b.scale,"z-index":1E3,display:"block"});b=c.fontInfo;null!=b&&b.useCustomTheme&&(null!=b.backgroundColor&&e.css({"background-color":ba(b.backgroundColor)}),null!=b.textFillColor&&e.css({color:ba(b.textFillColor)}),null!=b.fontSize&&e.css({"font-size":b.fontSize.split(" ").join("")}),null!=b.fontType&&e.css({"font-family":b.fontType}))}};d.getCurrentSectionInfo=function(){var b=d.getCurrentSection();return a.sectionInfo.find("#section-"+
b)};d.nextStep=function(){J();a.carousel.carousel("next");var b=d.getCurrentSection(),c=a.sectionInfo.find("#section-"+b),b=t();d.toggleActiveStep();if(1==d.getCurrentStep()&&(c=c.data("section-introduction"))){M();e.trigger(l.STEP_CHANGED,d);q();U(c);return}e.find(".carousel-inner .item:first").hasClass("active")?(a.playButtonIcon.attr("class","fa fa-fw fa-play fa-2x"),m=!1,p=r=0,O(),B(0),a.playHeadButton.parent().removeClass("hidden"),a.mouse.hide()):Q(b);M();e.trigger(l.STEP_CHANGED,d);q();n&&
(n[d.getOverallStep()-1]?m&&a.jplayer.jPlayer("play",n[d.getOverallStep()-1][0]/1E3):E())};d.goToOverallStep=function(b){var c=1,e,h=!1;for(e=1;!h;e++){var f=a.sectionInfo.find("#section-"+e).data("section-size");null!=f&&(f>=b?h=!0:(c++,b-=f))}d.goToStep(c,b)};d.goToStep=function(b,c){m=!1;J();a.playButtonIcon.attr("class","fa fa-fw fa-play fa-2x");a.mouse.stop();clearTimeout(u);a.dragOverlay.hide();if(1==b&&1<c||1<b)a.carousel.carousel(d.carouselStepNumber(b,c-1)),aa(0),a.mouse.show(),x=!0;else{var g=
e.find("img")[0];a.mouse.animate({left:a.carousel.position().left+Math.max((a.carousel.width()-g.width)/2,0),top:a.carousel.position().top+Math.max((a.carousel.height()-g.height)/2,0)},0);a.mouse.hide()}a.carousel.carousel(d.carouselStepNumber(b,c));b=a.carousel.find(".active").data("startTime");d.toggleActiveStep();r=0;(c=a.jplayer.data("jPlayer"))&&c.status&&(n?(b=d.getOverallStep(),n[b-1]?a.jplayer.jPlayer("pause",n[b-1][0]/1E3):E()):a.jplayer.jPlayer("pause",b/1E3));M();I();O();e.trigger(l.STEP_CHANGED,
d)};d.carouselStepNumber=function(b,c){if(1==b)return c-1;var d=0,e;for(e=1;e<b;e++){var f=a.sectionInfo.find("#section-"+e).data("section-size");null!=f&&(d+=f)}return d+c-1};var L=function(a,c){"scale"===c.prop&&($(this).css("transform","scale("+a+") translate3d(0, 0, 0)"),$(this).css("-webkit-transform","scale("+a+") translate3d(0, 0, 0)"),$(this).css("-moz-transform","scale("+a+") translate3d(0, 0, 0)"))},K=function(a){for(var c=0;c<a.tweens.length;c++){var d=a.tweens[c];"scale"===d.prop&&0==
d.start&&(d.start=ea,ea=d.end)}},da=function(){var b=new R;duration=t()/4;b.carouselWidth>b.naturalWidth&&(b.offset=(b.carouselWidth-b.naturalWidth)/2);var c=(parseInt(b.minX)+parseInt(b.width)/2)*b.scale+b.offset,d=(parseInt(b.minY)+parseInt(b.height)/2)*b.scale;a.inner.animate({top:-Math.min(Math.max(0,d/b.scale-b.carouselHeight/2),b.naturalHeight-b.carouselHeight),left:-Math.min(Math.max(0,c/b.scale-b.carouselWidth/2),b.naturalWidth-b.carouselWidth),scale:1/b.scale},{start:K,step:L,duration:duration})};
d.toggleSteps=function(){a.sideContainer.is(":visible")?(a.sideContainer.fadeOut(300),setTimeout(function(){a.showMeContainer.addClass("full");a.showMeContainer.addClass("transition")},300)):(a.showMeContainer.removeClass("full"),setTimeout(function(){a.sideContainer.fadeIn();a.showMeContainer.removeClass("transition");z()},500))};d.toggleFullscreen=function(){captureProjectUtils.toggleFullscreen(e,a,A(),function(b){(ca=b)?(a.showMeContainer.addClass("capture-fullscreen-height"),e.addClass("capture-fullscreen-overflow"),
a.inner.stop(),y(300)):(a.showMeContainer.removeClass("capture-fullscreen-height"),e.removeClass("capture-fullscreen-overflow"))})};d.play=function(){m||f()};d.pause=function(){m&&f()};d.togglePlayback=function(){f()};d.reset=function(){d.goToStep(1,1)};return d};