/*! -- File: test.js ( Input 0 ) -- */
var DKI;DKI||(DKI={});function getSubmitButtonWrapperClass(a){return 6==a.questionType?"button-position-popup":"button-position-"+player.submitButtonPosition}
DKI.TestQuestion=function(){var a=$(document.body).data("singlepage")?!0:!1;480>=screen.availWidth||$(document.body).width();var b={submit:function(c,h){var d=!1;"undefined"!=typeof dataStorage&&dataStorage.currentModule.forceTestEnd&&(d=dataStorage.currentModule.forceTestEnd);if(this.submitted){if(!a&&!this.isPracticeQuestion&&settings.enableTimerQuestions&&d)return $(document).trigger(DKI.Events.TestQuestion.forceEnd),!1;$(document).trigger(DKI.Events.TestQuestion.nextClicked);return null}this.submitted=
!0;this.getOptions();c&&(c.preventDefault(),c.stopPropagation());if(b.overMaxOptions.call(this))return alert(this.strings.tstchoicesLabel1+" "+this.maxSelections+" "+this.strings.tstchoicesLabel2),this.submitted=!1;if(!this.hasSelection.call(this)&&(!settings.enableTimerQuestions||settings.enableTimerQuestions&&!d)&&!confirm(this.strings.confirmQuestionNoSelection))return this.submitted=!1;this.submitButton.unbind();h=h?h:0;this.numAttempts++;if(a||this.isPracticeQuestion)h=b.scorePreview.call(this,
h),this.setScore(h);else{h=b.scoreExport.call(this,h,d);if(settings.enableTimerQuestions&&d)return $(document).trigger(DKI.Events.TestQuestion.forceEnd),!1;$(document).trigger(DKI.Events.TestQuestion.exportSubmitted)}100==h&&($(this.pageContainer).trigger(DKI.Events.TestQuestion.correct),this.numAttempts<this.question.attempts&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptSubmitted),this.numAttempts=this.question.attempts);this.numAttempts==this.question.attempts?($(this.pageContainer).trigger(DKI.Events.TestQuestion.submitted),
0>=h?$(this.pageContainer).trigger(DKI.Events.TestQuestion.incorrect):100>h&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.partiallyCorrect)):($(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptSubmitted),0>=h?$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptIncorrect):100>h&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.attemptPartiallyCorrect));return!1},overMaxOptions:function(){var c=!1,a=0;if(2==this.questionType||3==this.questionType){for(var b=this.getOptions(),
d=0;d<b.length;d++)1==b[d].value().checked&&a++;a>this.maxSelections&&(c=!0)}return c},atMaxOptions:function(){var c=!1,a=0;if(2==this.questionType||3==this.questionType){for(var b=this.getOptions(),d=0;d<b.length;d++){var g=$("input",b[d].wrapper);g.attr("attr-checked")&&"true"==g.attr("attr-checked").toString()&&a++}a==this.maxSelections&&(c=!0)}return c},showDefaultSubmit:function(){var c=this,a='\x3cdiv class \x3d "button-wrapper '+getSubmitButtonWrapperClass(c)+'"\x3e\x3cbutton role\x3d"button" tabindex\x3d"1" class\x3d"btn btn-primary btn-block dki-submit-button"\x3e'+
DKI.strings.runtime.buttonLabelSubmit+"\x3c/button\x3e\x3c/div\x3e";"popup"==player.submitButtonPosition||6==this.questionType?(6==this.questionType&&(a='\x3cdiv class \x3d "button-wrapper dragdrop"\x3e\x3cbutton role\x3d"button" tabindex\x3d"1" class\x3d"btn btn-primary btn-block dki-submit-button"\x3e'+DKI.strings.runtime.buttonLabelSubmit+"\x3c/button\x3e\x3c/div\x3e"),contentApi.showPopup({html:a,effect:"fade",style:"default",autoFocus:!1,popupType:{mod:"botRight dki-submit-button",modal:!1,type:"notification"},
id:"dki-submit-"+this.question.id,tabContent:!1,role:"application",afterShow:function(){c.settings.responsive&&$(c.pageContainer).css("padding-bottom",$("#action_popup_dki-submit-"+c.question.id).height());c.submitButton=$("#action_popup_dki-submit-"+c.question.id+" .dki-submit-button");c.submitButton.on(settings.clickEvent,function(){contentApi.submitQuestion()});c.positionSubmitButton()}})):(c.submitButton=$(a),"belowPage"==player.submitButtonPosition&&(submitPosition=$("\x3cdiv/\x3e",{"class":"submitButtonBelowPage"}),
$(".dki-authoring-row",this.pageContainer).last().after(c.submitButton)),"belowQuestionOptions"==player.submitButtonPosition&&6!=this.questionType&&(submitPosition=$("\x3cdiv/\x3e",{"class":"submitButtonBelowOptions"}),$(".dki-authoring-element[data-isquestionoption\x3d'true']",this.pageContainer).last().after(c.submitButton)),c.submitButton=c.submitButton.find("Button"),$(".try-again-wrapper").remove(),c.submitButton.on(settings.clickEvent,function(){contentApi.submitQuestion()}))},scorePreview:function(c){var h=
this.getOptions(),d=this.getCorrectCount(),e=0,g=0,f;c="undefined"===typeof c?0:c;var m=!1;if("pre"==this.prePost&&this.behaviour.reviewPreAnswers||"post"==this.prePost&&this.behaviour.reviewPostAnswers)m=!0;if(13==this.questionType)c=this.calculate(m);else if(11==this.questionType||12==this.questionType)c=this.calculate(),this.showInlineFeedback();else{for(var l=0;l<h.length;l++)f=h[l].score(),1===f?e++:-1===f&&g++,h[l].value(),b.showCorrectAnswers.call(this)&&h[l].showCorrect(m);c=this.calculate(d,
e,g,c)}!this.isPracticeQuestion&&a&&$(this.pageContainer).trigger(DKI.Events.TestQuestion.questionInReview);l=$(".dki-questionBody-element .dki-element-content",this.pageContainer);d={type:this.questionType,body:l.text().trim(),latency:(new Date).getTime()-this.startTime,options:[],data:this.getData()};for(l=0;l<h.length;l++)d.options[l]=h[l].value();"undefined"==typeof dataStorage||this.inReview||$(this.player.dataStorage).trigger(DKI.DataStorage.events.questionScored,{question:dataStorage.currentPage.question,
questionObject:d,score:c,test:this});$(".dki-authoring-element",this.pageContainer).has(".correct, .incorrect, .multiChoiceCorrect").css("zIndex",1E5);return c},scoreExport:function(c,a){for(var b=this.getOptions(),d={type:this.questionType,body:this.getBodyText(),latency:(new Date).getTime()-this.startTime,options:[],data:this.getData()},g=0;g<b.length;g++)d.options[g]=b[g].value(),this.behaviour.IncludeQuestionNumbering&&(d.options[g].text=$(".optionNumber",b[g].wrapper).text()+d.options[g].text);
return c=this.player.dataStorage.submitCurrentQuestion(d,c,a,this)},showCorrectFeedback:function(){return b.doShowFeedback.call(this,"correct")},showIncorrectFeedback:function(){return b.doShowFeedback.call(this,"incorrect")},showIncorrectAttemptFeedback:function(){return b.doShowFeedback.call(this,"incorrectAttempt")},showPartialFeedback:function(){return b.doShowFeedback.call(this,"partial")},showPartialAttemptFeedback:function(){return b.doShowFeedback.call(this,"partialAttempt")},doShowFeedback:function(c){var d=
this.getFeedbackConfig(),k=d[3==this.question.type?"incorrect":c],e=d.popup;"true"==e.use_course_default.toString()&&(e=contentApi.getDefaultFeedbackPopup());var g=this,f="",f=k.useDefault?f+contentApi.getDefaultFeedbackText(c):f+k.text,d=this.getOptionFeedback();""!=d&&(""!=f&&(f+="\x3chr/\x3e"),f+=d);var m=function(){8!=g.question.type&&(13!=g.question.type&&g.showInlineFeedback(),f&&contentApi.showPopup({ariaLabel:DKI.strings.doc["Question feedback header"],html:f,title:"",effect:"fade",style:function(){var a=
"success";if("incorrect"==c||"incorrectAttempt"==c)a="danger";else if("partial"==c||"partialAttempt"==c)a="warning";return a}(),autoFocus:!0,popupType:{mod:e.mod,modal:e.modal,type:e.type},id:"question_"+g.question.id+"_feedback",addClass:"DKI-questionFeedback",returnFocus:$("button.dki-try-again")[0]?$("button.dki-try-again")[0]:document.activeElement}))},d=function(){for(var a=this.page.actions,b=function(c){if("api"==c.type){if(c=c.parameters.method,"hideForward"==c||"hideBack"==c||"hideBoth"==
c||"showForward"==c||"showBack"==c||"showBoth"==c)return!0}else if("setVariable"==c.type||"sendXAPIStatement"==c.type)return!0;return!1},d=0;d<a.length;d++){if(a[d].trigger==DKI.Events.TestQuestion.submitted&&!b(a[d]))return!0;if(a[d].trigger==DKI.Events.TestQuestion.correct&&!b(a[d])){if("correct"==c)return!0}else if(a[d].trigger==DKI.Events.TestQuestion.incorrect&&!b(a[d])){if("incorrect"==c)return!0}else if(a[d].trigger!=DKI.Events.TestQuestion.partiallyCorrect||b(a[d])){if(a[d].trigger==DKI.Events.TestQuestion.attemptSubmitted&&
!b(a[d]))return!0;if(a[d].trigger==DKI.Events.TestQuestion.attemptIncorrect&&!b(a[d])){if("incorrectAttempt"==c)return!0}else if(a[d].trigger==DKI.Events.TestQuestion.attemptPartiallyCorrect&&!b(a[d])&&"partialAttempt"==c)return!0}else if("partial"==c)return!0}return!1},k=function(){var a='\x3cdiv class\x3d"try-again-wrapper '+getSubmitButtonWrapperClass(this)+'"\x3e\x3cspan class\x3d"remainingAttempts" tabindex\x3d"1"\x3e'+DKI.strings.runtime.txtRemainingAttempts+" "+(g.question.attempts-g.numAttempts)+
'\x3c/span\x3e\x3cbutton class\x3d"btn btn-primary dki-try-again" tabindex\x3d"1" onclick\x3d"contentApi.tryAgain();" data-dismiss\x3d"alert"\x3e'+DKI.strings.runtime.testTryAgain+"\x3c/button\x3e\x3cdiv\x3e";!g.inReview&&g.isPracticeQuestion&&g.question.show_try_again&&g.numAttempts<g.question.attempts&&("incorrectAttempt"==c||"partialAttempt"==c)?8!==g.questionType&&("popup"==player.submitButtonPosition||6==g.questionType?contentApi.showPopup({html:a,effect:"fade",style:"default",autoFocus:!0,popupType:{mod:"botRight dki-try-again",
modal:!1,type:"notification"},id:"dki-try-again-"+g.question.id,returnFocus:document.activeElement,tabContent:!1,role:"application",afterShow:function(){g.tryAgainButton=$("#content_dki-try-again-"+g.question.id+" .dki-try-again");g.positionSubmitButton();$("#content_dki-try-again-"+g.question.id+" .remainingAttempts").focus()}}):("belowPage"==player.submitButtonPosition&&$(".dki-authoring-row",g.pageContainer).last().after(a),"belowQuestionOptions"==player.submitButtonPosition&&6!=g.questionType&&
$(".dki-authoring-element[data-isquestionoption\x3d'true']",g.pageContainer).last().after(a),$(".dki-submit-button").remove(),$("#content_dki-try-again-"+g.question.id+" .remainingAttempts").focus())):(g.submitButton.text(g.strings.buttonLabelNext),g.submitButton.off(),g.submitButton.on(g.player.settings.clickEvent,$.proxy(function(c){g.submitButton.unbind(c);g.submitButton.hide();c.preventDefault();c.stopPropagation();g.page.isStandalonePage?$.fancybox.close():$(document).trigger(DKI.Events.TestQuestion.nextClicked)},
g)),(7==g.questionType||8==g.questionType&&!g.inReview)&&g.submitButton.trigger(g.player.settings.clickEvent))};if(b.showFeedback.call(this)){if(""!=f||this.hasInlineFeedback())setTimeout(k,100),this.inReview?setTimeout(function(){m()},500):m();else{if(8==g.question.type)return setTimeout(k,100),!1;if(g.inReview||g.isPracticeQuestion||a||dataStorage.currentModule.forceTestEnd||d.call(this))setTimeout(k,100);else return setTimeout(function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},
0),!1}return!0}8==g.question.type?setTimeout(k,100):g.inReview||g.isPracticeQuestion||a||dataStorage.currentModule.forceTestEnd||d.call(this)?setTimeout(k,100):setTimeout(function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},0);return!1},showFeedback:function(){return!this.behaviour||this.preview?!0:this.inReview||!this.behaviour.displayQuestionFeedback&&!this.isPracticeQuestion?this.inReview?"pre"==this.prePost&&this.behaviour.reviewPreFeedback?!0:"post"==this.prePost&&this.behaviour.reviewPostFeedback?
!0:!1:!1:!0},showCorrectAnswers:function(){return this.isPracticeQuestion||this.behaviour&&!this.preview?this.inReview&&("pre"==this.prePost&&this.behaviour.reviewPreAnswers||"post"==this.prePost&&this.behaviour.reviewPostAnswers)?!0:!1:!0}},d=function(c,d,k,e){var g=function(c){var a=$("label[for\x3d'"+c.attr("id")+"']",d.pageContainer);$(".content input[type\x3d'radio']",d.pageContainer).each(function(a,b){$("label[for\x3d'"+b.id+"']").removeClass("checked");b.id!=c.attr("id")&&$(b).prop("checked",
!1)});$(".input-group",d.pageContainer).removeClass("checked");c.prop("checked")?(a.addClass("checked"),a.closest(".input-group").addClass("checked")):a.removeClass("checked");$(".input-group input:checked",d.pageContainer).each(function(){$(this).closest(".input-group").addClass("checked")})};this.question=k;this.player=c;this.strings=c.strings;this.page=d;this.behaviour=this.player.behaviour;this.inReview=this.player.inReview;this.settings=this.player.settings;this.submitted=!1;this.prePost="";
this.pageContainer=this.page.pageContainer;this.questionElement=$("div[data-pagetype\x3d'question']",this.pageContainer);this.questionType=parseInt(this.questionElement.attr("data-questiontype"),10);this.startTime=null;this.submitButton=$(".dki-submit-button");this.scoreDisplay=$(".questionScoreDisplay");this.maxSelections=parseInt(this.questionElement.attr("data-max-selections"),10);this.freeFormMaxLength=4E3;this.numAttempts=0;this.isPracticeQuestion=e;this.isSinglePage=a;"undefined"!==typeof scormAPI&&
"SCORM"==scormAPI.strLMSStandard&&(this.freeFormMaxLength=255);this.getData=function(){};this.onShowReview=function(c){c()};this.showInlineFeedback=function(){};this.hasInlineFeedback=function(){return!1};switch(this.questionType){case 1:this.getCorrectCount=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.TrueFalseQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.TrueFalseQuestion.scoreOption,
this);this.calculate=$.proxy(DKI.TestQuestion.TrueFalseQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.TrueFalseQuestion.getOptionFeedback,this);$(".trueOption_label",this.pageContainer).text(this.strings.trueOptionLabel);$(".falseOption_label",this.pageContainer).text(this.strings.falseOptionLabel);break;case 2:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getOptions,
this);this.hasSelection=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.getOptionFeedback,this);this.randomizeOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestion.randomizeOptions,this);this.inReview||this.randomizeOptions();break;case 3:this.getCorrectCount=
$.proxy(DKI.TestQuestion.FreeFormQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.FreeFormQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.FreeFormQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.FreeFormQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.FreeFormQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.FreeFormQuestion.getOptionFeedback,this);break;case 4:this.getCorrectCount=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getCorrectCount,
this);this.getOptions=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.FillBlanksQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.FillBlanksQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.FillBlanksQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.FillBlanksQuestion.getOptionFeedback,this);break;case 5:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getCorrectCount,
this);this.getOptions=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultiplePulldownQuestion.getOptionFeedback,this);this.randomizeOptions=function(){$(".dki-multiPulldownOption-element select",
this.pageContainer).each(function(){for(var c=[],a=this.options.length-1;0<=a;a--)""!=$(this.options[a]).html()&&c.push(this.options[a]),this.remove(a);for(a=c.length;a--;){var b=Math.floor(Math.random()*(a+1)),d=c[a];c[a]=c[b];c[b]=d}this.innerHTML="";if(dkiUA.ie&&8>=dkiUA.ieVersion)for(this.add(new Option("","")),a=0;a<c.length;a++)this.add(c[a],a+1);else for(this.add(new Option("",""),null),a=0;a<c.length;a++)this.add(c[a],null);this.selectedIndex=0})};this.randomizeOptions();break;case 6:this.getCorrectCount=
$.proxy(DKI.TestQuestion.DragDropQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.DragDropQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.DragDropQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.DragDropQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.DragDropQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.DragDropQuestion.getOptionFeedback,this);break;case 7:this.getCorrectCount=$.proxy(DKI.TestQuestion.customQuestion.getCorrectCount,
this);this.getOptions=$.proxy(DKI.TestQuestion.customQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.customQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.customQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.customQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.customQuestion.getOptionFeedback,this);break;case 8:this.getCorrectCount=$.proxy(DKI.TestQuestion.captureQuestion.getCorrectCount,this);this.getOptions=
$.proxy(DKI.TestQuestion.captureQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.captureQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.captureQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.captureQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.captureQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.captureQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.captureQuestion.onShowReview,
this);this.getBodyText=$.proxy(DKI.TestQuestion.captureQuestion.getBodyText,this);break;case 9:this.getCorrectCount=$.proxy(DKI.TestQuestion.imageMapQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.imageMapQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.imageMapQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.imageMapQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.imageMapQuestion.calculate,this);this.getOptionFeedback=
$.proxy(DKI.TestQuestion.imageMapQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.imageMapQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.imageMapQuestion.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.imageMapQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.imageMapQuestion.hasInlineFeedback,this);this.getBodyText=$.proxy(DKI.TestQuestion.imageMapQuestion.getBodyText,this);break;case 10:this.getCorrectCount=
$.proxy(DKI.TestQuestion.scenarioQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.scenarioQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.scenarioQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.scenarioQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.scenarioQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.scenarioQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.scenarioQuestion.getData,
this);this.onShowReview=$.proxy(DKI.TestQuestion.scenarioQuestion.onShowReview,this);this.getBodyText=$.proxy(DKI.TestQuestion.scenarioQuestion.getBodyText,this);this.showDefaultSubmit=$.proxy(b.showDefaultSubmit,this);break;case 11:this.getCorrectCount=$.proxy(DKI.TestQuestion.matchingQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.matchingQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.matchingQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.matchingQuestion.scoreOption,
this);this.calculate=$.proxy(DKI.TestQuestion.matchingQuestion.calculate,this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.matchingQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.matchingQuestion.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.matchingQuestion.hasInlineFeedback,this);this.getFeedbackConfig=
$.proxy(DKI.TestQuestion.matchingQuestion.getFeedbackConfig,this);this.getBodyText=$.proxy(DKI.TestQuestion.matchingQuestion.getBodyText,this);break;case 12:this.getCorrectCount=$.proxy(DKI.TestQuestion.sequencingQuestion.getCorrectCount,this);this.getOptions=$.proxy(DKI.TestQuestion.sequencingQuestion.getOptions,this);this.hasSelection=$.proxy(DKI.TestQuestion.sequencingQuestion.hasSelection,this);this.scoreOption=$.proxy(DKI.TestQuestion.sequencingQuestion.scoreOption,this);this.calculate=$.proxy(DKI.TestQuestion.sequencingQuestion.calculate,
this);this.getOptionFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.getOptionFeedback,this);this.getData=$.proxy(DKI.TestQuestion.sequencingQuestion.getData,this);this.onShowReview=$.proxy(DKI.TestQuestion.sequencingQuestion.onShowReview,this);this.showInlineFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.showInlineFeedback,this);this.hasInlineFeedback=$.proxy(DKI.TestQuestion.sequencingQuestion.hasInlineFeedback,this);this.getFeedbackConfig=$.proxy(DKI.TestQuestion.sequencingQuestion.getFeedbackConfig,
this);this.getBodyText=$.proxy(DKI.TestQuestion.sequencingQuestion.getBodyText,this);break;case 13:this.getCorrectCount=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getCorrectCount,this),this.getOptions=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getOptions,this),this.hasSelection=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.hasSelection,this),this.scoreOption=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.scoreOption,this),this.calculate=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.calculate,
this),this.getOptionFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getOptionFeedback,this),this.getData=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getData,this),this.onShowReview=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.onShowReview,this),this.showInlineFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.showInlineFeedback,this),this.hasInlineFeedback=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.hasInlineFeedback,this),this.getBodyText=$.proxy(DKI.TestQuestion.MultipleChoiceQuestionWidget.getBodyText,
this)}this.player.questionPage=this;var f=this;$(this.pageContainer).on(this.settings.clickEvent,".dki-trueFalse-selector, .dki-multiChoice-selector, .dki-multiChoiceOption-element .dki-element-anchor, .dki-trueFalseOption-element .dki-element-anchor, .dki-multiChoiceOption-element input, .dki-multiChoiceOption-element label, .dki-trueFalseOption-element input",function(c){var a=$(this).parent().find("input");if(a.prop("disabled"))return c.stopPropagation(),c.preventDefault(),!1;var d=$("label[for\x3d'"+
a.attr("id")+"']",f.pageContainer);if(!d.hasClass("checked")&&b.atMaxOptions.call(f)&&"radio"!=a.attr("type"))return alert(f.strings.tstchoicesLabel1+" "+f.maxSelections+" "+f.strings.tstchoicesLabel2),c.stopPropagation(),c.preventDefault(),a.prop("checked",a.attr("attr-checked")&&"true"==a.attr("attr-checked").toString()),!1;a.attr("attr-checked")&&"true"==a.attr("attr-checked").toString()?"checkbox"==a.attr("type")&&a.attr("attr-checked",!1):a.attr("attr-checked",!0);a.prop("checked",a.attr("attr-checked")&&
"true"==a.attr("attr-checked").toString());g(a);var h=$(this).closest(".dki-authoring-element");$("*[tabindex]:not([tabindex\x3d'-1'])",h).focus();"checkbox"!=a.attr("type")||a[0]!=c.target&&d[0]!=c.target||c.stopPropagation()});$(".dki-freeFormOption-element textarea").attr("maxlength",this.freeFormMaxLength);$(this.pageContainer).on("keyup",".dki-freeFormOption-element textarea",function(c){c=$(this).val();c.length>f.freeFormMaxLength&&(c=c.substr(0,f.freeFormMaxLength),$(this).val(c))});$("input",
this.pageContainer).on("focus",function(c){$(this).closest(".input-group-addon").addClass("focus-within")});$("input",this.pageContainer).on("blur",function(c){$(".input-group-addon.focus-within").removeClass("focus-within")});for(var m in DKI.Events.TestQuestion)$(this.pageContainer).off(DKI.Events.TestQuestion[m]);$(this.pageContainer).on(DKI.Events.TestQuestion.submitted,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.submitted,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.correct,
function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.correct,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.incorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.incorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.partiallyCorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.partiallyCorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptSubmitted,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptSubmitted,
f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptIncorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptIncorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.attemptPartiallyCorrect,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.attemptPartiallyCorrect,f.page)});$(this.pageContainer).on(DKI.Events.TestQuestion.questionInReview,function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.questionInReview,f.page)});$(document).on(DKI.Events.TestQuestion.retry,
function(){f.page.actionAPI.onPageEvent(DKI.Events.TestQuestion.retry,f.page)});$.each(this.page,function(c){"undefined"==typeof f[c]&&DKI.isFunction(this)&&(f[c]=$.proxy(f.page[c],f.page))})};DKI.applyIf(d.prototype,{setPrePost:function(c){this.prePost=c?c:"post"},setScore:function(c,a,d){c=void 0!==c&&null!==c?parseFloat(c,10):0;var e=!0;this.isPracticeQuestion&&(e=this.numAttempts==this.question.attempts);7!==this.questionType&&(c=0>=c?e?b.showIncorrectFeedback.call(this):b.showIncorrectAttemptFeedback.call(this):
100===c?b.showCorrectFeedback.call(this):e?b.showPartialFeedback.call(this):b.showPartialAttemptFeedback.call(this))&&$(document).trigger(DKI.Events.TestQuestion.feedbackShown);c=this.getOptions();for(e=0;e<c.length;e++)c[e].enabled(!1);this.inReview&&($(".questionScoreLabel").text(player.strings.txtScore+(" "!=player.strings.txtScore.slice(-1)?" ":"")),$(".questionScore").text(a+" / "+d+" "+this.strings.txtPoints),$(document.body).hasClass("phone")?this.scoreDisplay.show():this.scoreDisplay.fadeIn(200))},
setOptions:function(c,a){for(var b=this.getOptions(),d=0;d<b.length;d++)b[d].value(c[d]),b[d].enabled(!1),b[d].correctResponse(a[d]);2==this.questionType&&$(".dki-multiChoiceOption-element .multiChoiceContentWrapper").css("visibility","")},showReview:function(c,a,d,e){this.inReview=!0;this.numAttempts=this.question.attempts;this.setPrePost(c);this.setOptions(a,d);var g=7==this.questionType?[e.score]:[];this.onShowReview($.proxy(function(){b.scorePreview.apply(this,g);this.setScore(e.score,e.points,
e.weight);$(this.pageContainer).trigger(DKI.Events.TestQuestion.questionInReview);this.question.disable_submit||this.settings.responsive||7!=this.questionType&&($(document.body).hasClass("phone")?this.submitButton.show():this.submitButton.fadeIn(500))},this))},showCorrectAnswers:function(){for(var c=this.getOptions(),a=0;a<c.length;a++)c[a].showCorrect(!0)},tryAgain:function(){this.reset({doNotResetAttempts:!0});this.tryAgainButton=null;$(document).trigger(DKI.Events.TestQuestion.retry);this.start()},
submitQuestion:function(c){b.submit.call(this,null,c)},start:function(){this.startTime=(new Date).getTime();var c=this;this.page.resize();this.page.start();this.startOptions();!this.question.disable_submit&&7!=this.question.type&&(10!==this.question.type&&8!=this.question.type||this.inReview)&&b.showDefaultSubmit.call(this);6==this.questionType&&($(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).draggable({revert:function(c){$(this).data("draggable").originalPosition=
{top:settings.responsive?0:$(this).data("y"),left:settings.responsive?0:$(this).data("x")};if(c)$(this).trigger(DKI.ContentPage.events.elementDragDropped);else return $(this).css("z-index",$(this).data("elementno")),$(this).data("reverted",!0),$(this).trigger(DKI.ContentPage.events.elementDragReverted),!0},drag:function(c,a){c=$(this).data("initialPageYOffset");a.position.top+=c;DKI.utility.dragFix(a)},start:function(c,a){1!=$(this).data("reverted")&&"undefined"!=typeof $(this).data("reverted")||
$(this).data("origPosition",$(this).position());$(this).parent().css("position","static");$(this).data("reverted",!1);c=$(this).data("title");""==c&&(c=$(this).text());$(this).data("dropData",{id:$(this).data("dragdropid"),elementId:$(this).data("id"),title:c,target:{id:null,title:"No Target"},x:$(this).data("x"),y:$(this).data("y"),scale:settings.scale});$(this).data("initialPageYOffset",document.documentElement.scrollTop);$(this).trigger(DKI.ContentPage.events.elementDragStarted);$(document).trigger(DKI.Events.TestQuestion.dragStarted)},
stop:function(c,a){$(this).data("reverted")?($(this).css("z-index",$(this).data("elementno")),settings.responsive&&$(this).css({top:"",left:""}),$(this).data("draggable").originalPosition={top:$(this).data("y"),left:$(this).data("x")}):$(this).css("z-index",1E5);$(this).trigger(DKI.ContentPage.events.elementDragStopped);$(document).trigger(DKI.Events.TestQuestion.dragStopped)},stack:".dkiContentFrame.current .dki-authoring-element[data-is-droppable\x3dtrue][data-isf\x3dtrue], .fancybox-content .dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue], .dkiContentFrame.current .dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",
scroll:settings.responsive,zIndex:1E5,disabled:!1}),$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue], .dki-authoring-element-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).droppable({accept:".dkiContentFrame.current .dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue], .fancybox-content .dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",tolerance:"pointer",out:function(c,
a){$(this).trigger(DKI.ContentPage.events.elementDropOut)},over:function(c,a){$(this).trigger(DKI.ContentPage.events.elementDropOver)},drop:function(a,b){a=b.draggable.data("title");""==a&&(a=b.draggable.text());var d=$(this).data("title");""==d&&(d=$(this).text());var g=function(){},f=b.draggable.position(),m=settings.scale;!settings.responsive&&b.helper.closest(".fancybox-container").length&&(m*=settings.claroLightboxScaling);if(c.question.parameters.snapToCenter&&"true"==c.question.parameters.snapToCenter.toString()){if($(this).hasClass("dki-authoring-element-element")){var l=
0,p=0;settings.responsive?(l=b.draggable.height()/2+b.draggable.parent().offset().top+parseInt(b.draggable.css("margin-top")),p=b.draggable.width()/2+b.draggable.parent().offset().left+parseInt(b.draggable.css("margin-left"))):(l=b.draggable.height()/2,p=b.draggable.width()/2);if($(this).closest(".dki-authoring-element").hasClass("stackable_element")){var f=$(this).offset(),n=$(this).closest(".dki-authoring-element").data("scaleRatio")||1;f.top/=m;f.left/=m;l=f.top+$(this).height()*n/2-l;p=f.left+
$(this).width()*n/2-p}else f=$(this).offset(),f.top/=m,f.left/=m,n=$(this).find("\x3e.dki-authoring-content-wrapper").first(),l=f.top+parseInt(n.css("padding-top"))+(n.height()-parseInt(n.css("padding-bottom")))/2-l,p=f.left+parseInt(n.css("padding-left"))+(n.width()-parseInt(n.css("padding-left")))/2-p}else settings.responsive?(f=$(this).offset(),p=b.draggable.find("\x3e.dki-authoring-content-wrapper").first(),n=$(this).find("\x3e.dki-authoring-content-wrapper").first(),l=f.top+parseInt(n.css("padding-top"))+
(n.height()-parseInt(n.css("padding-bottom")))/2-p.outerHeight()/2-(b.draggable.data("origPosition").top+b.draggable.parent().offset().top+parseInt(b.draggable.css("margin-top"))),p=f.left+parseInt(n.css("padding-left"))+(n.width()-parseInt(n.css("padding-left")))/2-p.outerWidth()/2-(b.draggable.parent().offset().left+parseInt(b.draggable.css("margin-left")))):(f=$(this).position(),l=f.top+$(this).height()/2-b.draggable.height()/2,p=f.left+$(this).width()/2-b.draggable.width()/2);f={top:l,left:p};
b.draggable.animate({top:l/m+"px",left:p/m+"px"},125,g)}b.draggable.data("dropData",{id:b.draggable.data("dragdropid"),elementId:b.draggable.data("id"),title:a,target:{id:$(this).data("dragdropid"),title:d},x:f.left,y:f.top,scale:m});$(this).trigger(DKI.ContentPage.events.elementDropDropped)},disabled:!1}));8==this.questionType&&DKI.TestQuestion.captureQuestion.init(this);9==this.questionType&&DKI.TestQuestion.imageMapQuestion.init(this);10==this.questionType&&DKI.TestQuestion.scenarioQuestion.init(this);
11==this.questionType&&DKI.TestQuestion.matchingQuestion.init(this);12==this.questionType&&DKI.TestQuestion.sequencingQuestion.init(this);13==this.questionType&&DKI.TestQuestion.MultipleChoiceQuestionWidget.init(this)},reset:function(c){c=DKI.applyIf(c,{doNotResetAttempts:!1,timeout:0});var a=this;contentApi.destroyPopup("question_"+this.question.id+"_feedback");contentApi.destroyPopup("dki-submit-"+this.question.id);contentApi.destroyPopup("dki-try-again-"+this.question.id);a.settings.responsive&&
$(a.pageContainer).css("padding-bottom","");a.submitButton.hide();a.submitButton.unbind();var b=function(){a.submitted=!1;c.doNotResetAttempts||(a.numAttempts=0);c.timeout=0;a.page.reset(c);a.resetOptions();6==a.questionType&&($(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",a.pageContainer).draggable("option","disabled",!0),$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",a.pageContainer).droppable("option","disabled",!0))};
0<c.timeout?setTimeout(b,c.timeout):b()},startOptions:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)a[b].start()},resetOptions:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)a[b].reset();2==this.question.type&&this.randomizeOptions()},onWindowResize:function(){this.page.onWindowResize();this.positionSubmitButton()},positionSubmitButton:function(){if(this.submitButton.is(":visible")){var a=this.submitButton.closest(".notification");if(settings.responsive){var b=$("#contentFrame").offset(),
d=b.left+$("#contentFrame").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right,e=parseInt($(".bgRepeater").css("padding-bottom").split("px")[0],10),e=e+settings.course.parameters.submitButtonOffset.bottom;a.css({left:0>d?0:d,bottom:e,right:"auto"});$("#skipToNavigation").length&&$("#skipToNavigation").before(a.detach());this.tryAgainButton&&(a=this.tryAgainButton.closest(".notification"),d=b.left+$("#contentFrame").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right,
a.css({left:0>d?0:d,bottom:e,right:"auto"}),$("#skipToNavigation").length&&$("#skipToNavigation").before(a.detach()))}else b=$(".bgRepeater").offset(),b.top/=settings.scale,b.left/=settings.scale,d=b.left+$(".bgRepeater").width()-settings.course.parameters.submitButtonOffset.right,e=b.top+$(".bgRepeater").height()-settings.course.parameters.submitButtonOffset.bottom,d=Math.min(d,window.innerWidth/settings.scale)-a.outerWidth(),e=Math.min(e,window.innerHeight/settings.scale)-a.outerHeight(),a.css({top:e,
left:d,bottom:"auto",right:"auto"}),$("#skipToNavigation").length&&$("#skipToNavigation").before(a.detach()),this.tryAgainButton&&(a=this.tryAgainButton.closest(".notification"),d=b.left+$(".bgRepeater").width()-a.outerWidth()-settings.course.parameters.submitButtonOffset.right,a.css({top:e,left:d,bottom:"auto",right:"auto"}),$("#skipToNavigation").length&&$("#skipToNavigation").before(a.detach()))}},canShowFeedback:function(){return b.showFeedback.call(this)},canShowCorrectAnswers:function(){return b.showCorrectAnswers.call(this)},
getFeedbackConfig:function(a){return this.question.parameters.feedback},getBodyText:function(){return $(".dki-questionBody-element .dki-element-content",this.pageContainer).text()}});return d}();
DKI.TestQuestion.TrueFalseQuestion={calculate:function(a,b,d){return 1>b?0:100},getCorrectCount:function(){return 1},getOptions:function(){for(var a=$(".dki-trueFalseOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var h=$("input",a[c])[0];d=parseInt(h.getAttribute("data-order"),"10")-1;for(var k=null,e=0;e<this.question.options.length;e++)if(this.question.options[e].element_id==$(a[c]).data("id")){k=this.question.options[e];break}b[d]=new DKI.TestQuestion.TrueFalseOption(h,a[c],k)}return b},
getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(1==a[b].value())return!0;return!1}};
DKI.TestQuestion.TrueFalseOption=function(a,b,d){this.optionElement=a;this.optionValue=$(a).next();this.wrapper=b;this.choice=d;this.getFeedback=function(){return""};this.correctResponse=function(a){if(null!=a&&void 0!=a)$(this.optionElement).data("correctresponse",a.correct);else return $(this.optionElement).data("correctresponse")};this.isCorrect=function(){return this.choice.parameters.correct};this.enabled=function(a){if(void 0!==a&&null!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};
this.value=function(a){if(void 0!==a&&null!==a)1==a||1==a?(this.optionElement.checked=!0,$("label",this.wrapper).addClass("checked")):(this.optionElement.checked=!1,$("label",this.wrapper).removeClass("checked"));else return this.optionElement.checked?1:0};this.score=function(){return 1==this.value()&&this.isCorrect()?this.value():0};this.showCorrect=function(a){1==this.value()&&this.isCorrect()?($(".dki-authoring-content-wrapper",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&
($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.correctChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.correctChoiceText+"\x3c/div\x3e")))):1==this.value()&&($(".dki-authoring-content-wrapper",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.incorrectChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$("label",this.wrapper).text()+". "+settings.incorrectChoiceText+"\x3c/div\x3e"))));a&&this.isCorrect()&&$(".dki-authoring-content-wrapper",this.wrapper).addClass("multiChoiceCorrectResponse")};this.reset=function(){$(".dki-authoring-content-wrapper",this.wrapper).removeClass("correct").removeClass("incorrect").removeClass("multiChoiceCorrectResponse").removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();$(this.optionElement).prop("checked",!1);$(this.optionElement).attr("attr-checked",
!1);"none"!=$(this.optionElement).css("display")&&($(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex),this.optionElement.tabIndex=-1);this.optionValue.removeClass("checked");var a=$(this.optionElement).closest(".input-group");a[0]&&a.removeClass("checked").find(".checked").removeClass("checked");this.enabled(!0)};this.start=function(){"none"!=$(this.optionElement).css("display")&&(this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex"),$(".dki-element-anchor",
this.wrapper).attr("tabIndex",-1))}};
DKI.TestQuestion.MultipleChoiceQuestion={calculate:function(a,b,d){return d>b?0:(b-d)/a*100},getCorrectCount:function(){for(var a=0,b=this.getOptions(),d=0;d<b.length;d++)b[d].choice.parameters.correct&&a++;return a},getOptions:function(){for(var a=$(".dki-multiChoiceOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var h=$("input",a[c])[0];d=parseInt(h.getAttribute("data-order"),"10")-1;for(var k=null,e=0;e<this.question.options.length;e++)if(this.question.options[e].element_id==$(a[c]).data("id")){k=
this.question.options[e];break}b[d]=new DKI.TestQuestion.MultipleChoiceOption(h,a[c],k)}return b},randomizeOptions:function(){for(var a=$(".dki-multiChoiceOption-element[data-randomized\x3d'true']",this.pageContainer),b=[],d=[],c=[],h=[],k=this.getOptions(),e=0;e<k.length;e++)k[e].wrapper.data("randomized")&&h.push(e);$.each(a,function(a,c){var e=settings.responsive?0:$(c).data("y"),h=settings.responsive?0:$(c).data("x");b[a]={top:e,left:h,numbering:$(c).find(".optionNumber").text(),key:a};$(c).before("\x3cdiv class\x3d'RandomPlaceHolder' id\x3d'RandomPlaceHolder"+
a+"'\x3e\x3c/div\x3e");d[a]=$(c).detach()});a=d.length;for(e=0;e<a;e++)c.push(d.splice(Math.floor(Math.random()*d.length),1)[0]);for(e=0;e<a;e++)$(c[e]).data("y",b[e].top).data("x",b[e].left).data("numbering",b[e].numbering).data("feedbackOrder",h[e]+1).css({left:b[e].left,top:b[e].top}),$(".optionNumber",c[e]).text(b[e].numbering),$("#RandomPlaceHolder"+b[e].key,this.pageContainer).before(c[e]);$(".RandomPlaceHolder",this.pageContainer).remove();$(".dki-multiChoiceOption-element .multiChoiceContentWrapper").css("visibility",
"")},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=[],c=0;c<b.length;c++){var h;h=b[c].wrapper.data("randomized")?parseInt(b[c].wrapper.data("feedbackOrder"),"10"):parseInt(b[c].optionElement.getAttribute("data-order"),"10");d[h-1]=b[c]}for(c=0;c<d.length;c++)this.question.include_selection_feedback&&1==d[c].value().checked?a+=d[c].getFeedback():this.question.include_correct_feedback&&d[c].isCorrect()?a+=d[c].getFeedback():this.question.include_incorrect_feedback&&!d[c].isCorrect()&&
(a+=d[c].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(1==a[b].value().checked)return!0;return!1}};
DKI.TestQuestion.MultipleChoiceOption=function(a,b,d){this.optionElement=a;this.optionValue=$(a).next();this.wrapper=$(b);this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");b&&(b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+$(".optionNumber",this.wrapper).text(),a=a+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e"+
b+"\x3c/span\x3e\x3c/div\x3e");return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correct);else return this.optionElement.getAttribute("data-correctresponse")};this.isCorrect=function(){return this.choice.parameters.correct};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!==a){if(1==a.checked?(this.optionElement.checked=
!0,$(".input-group, label",this.wrapper).addClass("checked")):(this.optionElement.checked=!1,$(".input-group, label",this.wrapper).removeClass("checked")),this.wrapper.data("randomized")){var b=$("#"+a.elementIdReplaced+"_wrapper");this.wrapper.css({left:b.data("x"),top:b.data("y")});$(".optionNumber",this.wrapper).text(b.data("numbering"));this.wrapper.data("feedbackOrder",a.feedbackOrder)}}else return a={text:this.choice.content,plainText:$("\x3cdiv\x3e").html(this.choice.content).text().trim(),
elementIdReplaced:null,feedbackOrder:null},this.wrapper.data("randomized")&&(a.elementIdReplaced=this.wrapper.data("elementIdReplaced"),a.feedbackOrder=this.wrapper.data("feedbackOrder")),a.checked=this.optionElement.checked?1:0,a};this.score=function(){return 1==this.value().checked&&this.isCorrect()?1:1!=this.value().checked||this.isCorrect()?0:-1};this.showCorrect=function(a){1==this.value().checked&&(this.isCorrect()?($(".dki-authoring-content-wrapper",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&
($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.correctChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$("label",this.wrapper).text()+". "+settings.correctChoiceText+"\x3c/div\x3e")))):($(".dki-authoring-content-wrapper",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&($(".dki-authoring-content-wrapper",this.wrapper).attr("title",settings.incorrectChoiceText),$("label",this.wrapper).prepend($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$("label",this.wrapper).text()+". "+settings.inorrectChoiceText+"\x3c/div\x3e")))));a&&this.isCorrect()&&$(".dki-authoring-content-wrapper",this.wrapper).addClass("multiChoiceCorrectResponse")};this.reset=function(){$(".dki-authoring-content-wrapper",this.wrapper).removeClass("correct").removeClass("incorrect").removeClass("multiChoiceCorrectResponse").removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();$(this.optionElement).prop("checked",!1);"none"!=$(this.optionElement).css("display")&&
($(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex),this.optionElement.tabIndex=-1);this.optionValue.removeClass("checked");$(this.optionElement).attr("attr-checked",!1);$(".optionNumber",this.wrapper).text(this.wrapper.data("numbering"));this.wrapper.data("feedbackOrder",null);this.wrapper.data("elementIdReplaced",null);var a=$(this.optionElement).closest(".input-group");a[0]&&a.removeClass("checked").find(".checked").removeClass("checked");this.enabled(!0)};this.start=
function(){"none"!=$(this.optionElement).css("display")&&(this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex"),$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1))}};
DKI.TestQuestion.FillBlanksQuestion={calculate:function(a,b,d){return b/a*100},getCorrectCount:function(){return this.getOptions().length},getOptions:function(){for(var a=$(".dki-fillBlanksOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var h=$("input",a[c])[0];d=parseInt(h.getAttribute("data-order"),"10")-1;for(var k=null,e=0;e<this.question.options.length;e++)if(this.question.options[e].element_id==$(a[c]).data("id")){k=this.question.options[e];break}b[d]=new DKI.TestQuestion.FillBlanksOption(h,
$(a[c]),k)}return b},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=0;d<b.length;d++)this.question.include_correct_feedback&&1==b[d].score()?a+=b[d].getFeedback():this.question.include_incorrect_feedback&&0==b[d].score()&&(a+=b[d].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.FillBlanksOption=function(a,b,d){this.optionElement=a;this.wrapper=b;this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");b&&(b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+$(".optionNumber",this.wrapper).text(),a=a+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e"+b+"\x3c/span\x3e\x3c/div\x3e");
return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correctValues);else return this.optionElement.getAttribute("data-correctresponse")};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).val(a);else return $.trim($(this.optionElement).val()).toLowerCase()};this.isCorrect=function(){return 1==
this.score()?!0:!1};this.score=function(){for(var a=this.choice.parameters.correctValues,b=0;b<a.length;b++){var d=$.trim(a[b]).toLowerCase(),e=this.value();$.isNumeric(d)&&(d=parseFloat(d),e=parseFloat(e.replace(/\,|\s/g,"")));d=$("\x3cspan\x3e"+d+"\x3c/span\x3e").text().trim();if(e==d)return 1}return 0};this.showCorrect=function(a){1==this.score()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).val("");$(".dki-element-anchor",this.wrapper).attr("tabIndex",
this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.MultiplePulldownQuestion={calculate:function(a,b,d){return b/a*100},getCorrectCount:function(){return this.getOptions().length},getOptions:function(){for(var a=$(".dki-multiPulldownOption-element",this.pageContainer),b=[],d,c=0;c<a.length;c++){var h=$("select",a[c])[0];d=parseInt(h.getAttribute("data-order"),"10")-1;for(var k=null,e=0;e<this.question.options.length;e++)if(this.question.options[e].element_id==$(a[c]).data("id")){k=this.question.options[e];break}b[d]=new DKI.TestQuestion.MultiplePulldownOption(h,
$(a[c]),k)}return b},getOptionFeedback:function(){for(var a="",b=this.getOptions(),d=0;d<b.length;d++)this.question.include_correct_feedback&&1==b[d].score()?a+=b[d].getFeedback():this.question.include_incorrect_feedback&&0==b[d].score()&&(a+=b[d].getFeedback());return a},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.MultiplePulldownOption=function(a,b,d){this.optionElement=a;this.wrapper=b;this.choice=d;this.getFeedback=function(){var a="",b=this.wrapper.data("feedback");b&&(b=b.replace(/&quot;/g,'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),a=a+"\x3cdiv class\x3d'optionFeedbackWrapper'\x3e\x3cspan class\x3d'optionFeedbackNumbering'\x3e"+$(".optionNumber",this.wrapper).text(),a=a+"\x3c/span\x3e\x3cspan class\x3d'optionFeedbackContent'\x3e"+b+"\x3c/span\x3e\x3c/div\x3e");
return a};this.correctResponse=function(a){if(null!=a&&void 0!=a)this.optionElement.setAttribute("data-correctresponse",a.correctValue);else return this.optionElement.getAttribute("data-correctresponse")};this.isCorrect=function(){var a=$('\x3cselect\x3e\x3coption value\x3d"'+escape(this.choice.parameters.correctValue.trim())+'"\x3e'+this.choice.parameters.correctValue+"\x3c/option\x3e\x3c/select\x3e");return escape(this.value().trim())==a.value()?!0:!1};this.enabled=function(a){if(null!==a&&void 0!==
a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!=a)$(this.optionElement).val(a);else return $(this.optionElement).val()};this.score=function(){return this.isCorrect()?1:0};this.showCorrect=function(a){1==this.score()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){this.optionElement.selectedIndex=0;$(".dki-element-anchor",this.wrapper).attr("tabIndex",
this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.FreeFormQuestion={calculate:function(){return""!==this.getOptions()[0].value().trim()?100:0},getCorrectCount:function(){return 0},getOptions:function(){for(var a=$(".dki-freeFormOption-element textarea",this.pageContainer),b=[],d,c=0;c<a.length;c++)d=parseInt(a[c].getAttribute("data-order"),"10")-1,b[d]=new DKI.TestQuestion.FreeFormOption(a[c],$(a[c]).closest(".dki-authoring-element"));return b},getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),
b=0;b<a.length;b++)if(""==a[b].value())return!1;return!0}};
DKI.TestQuestion.FreeFormOption=function(a,b){this.optionElement=a;this.wrapper=b;this.correctResponse=function(){return""};this.getFeedback=function(){return""};this.isCorrect=function(){return""!=this.value()?!0:!1};this.enabled=function(a){if(null!==a&&void 0!==a)this.optionElement.disabled=!a;else return!this.optionElement.disabled};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).val(a);else return $(this.optionElement).val()};this.score=function(){return 0};this.showCorrect=
function(a){this.isCorrect()?($(".dki-question-option",this.wrapper).addClass("correct"),""!=settings.correctChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+$(this.optionElement).val()+". "+settings.correctChoiceText+"\x3c/div\x3e"))):($(".dki-question-option",this.wrapper).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(".dki-question-option",this.wrapper).attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback' tabIndex\x3d'1'\x3e"+
$(this.optionElement).val()+". "+settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).val("");$(".dki-element-anchor",this.wrapper).attr("tabIndex",this.optionElement.tabIndex);this.optionElement.tabIndex=-1;$(".dki-question-option",this.wrapper).removeClass("correct");$(".dki-question-option",this.wrapper).removeClass("incorrect");$(".dki-question-option",this.wrapper).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};
this.start=function(){this.optionElement.tabIndex=$(".dki-element-anchor",this.wrapper).data("tabIndex");$(".dki-element-anchor",this.wrapper).attr("tabIndex",-1)}};
DKI.TestQuestion.DragDropQuestion={calculate:function(a,b,d){return 0==a&&0==b&&0==d?0:b/a*100},getCorrectCount:function(){return $(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).length},getOptions:function(){for(var a=$(".dki-authoring-element[data-is-draggable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer),b=[],d=0;d<a.length;d++){for(var c=null,h=$(a[d]).data("id"),k=0;k<this.question.options.length;k++)this.question.options[k].element_id==
h&&(c=this.question.options[k]);b[d]=new DKI.TestQuestion.DragDropOption(a[d],c)}return b},getOptionFeedback:function(){return""},hasSelection:function(){for(var a=this.getOptions(),b=0;b<a.length;b++)if(null!=a[b].value().target.id)return!0;return!1}};
DKI.TestQuestion.customQuestion={calculate:function(a,b,d,c){try{if(isNaN(c))throw"Invalid data. Please provide a numeric score.";c=parseInt(c,10);c=0>c?0:c;return 100<c?100:c}catch(h){return 0}},getOptions:function(){return[]},getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return!0}};
DKI.TestQuestion.DragDropOption=function(a,b){this.optionElement=a;this.questionOption=b;this.correctResponse=function(a){a=this.value();$(this.optionElement).css({top:a.y/a.scale+"px",left:a.x/a.scale+"px"});return null};this.getFeedback=function(){return""};this.enabled=function(a){if(null!==a&&void 0!==a){$(this.optionElement).draggable({disabled:!a});var b=0;$(".dki-authoring-element[data-is-droppable\x3dtrue][data-isquestionelement\x3dtrue]",this.pageContainer).each(function(){var a=parseInt($(this).css("z-index"),
10);a>b&&(b=a)});a=$(this.optionElement).data("elementno");$(this.optionElement).css("z-index",Math.max(b+1,a));$(this.optionElement).parent(".dki-authoring-group").css("position","static")}else return!1};this.value=function(a){if(null!==a&&void 0!==a)$(this.optionElement).data("dropData",a);else{a=$(this.optionElement).data("dropData");if(!a){a=$(this.optionElement).position();var b=$(this.optionElement).data("title");""==b&&(b=$(this.optionElement).text());a={id:$(this.optionElement).data("dragdropid"),
elementId:$(this.optionElement).data("id"),title:b,target:{id:null,title:"No Target"},x:a.left,y:a.top,scale:settings.scale}}return a}};this.isCorrect=function(){return 1==this.score()?!0:!1};this.score=function(){var a=this.value().target.id;if(a){for(var b=0;b<this.questionOption.parameters.correctTargets.length;b++)if(a.toString().toLowerCase()==this.questionOption.parameters.correctTargets[b].toString().toLowerCase())return 1;return-1}return 0<this.questionOption.parameters.correctTargets.length?
-1:1};this.showCorrect=function(a){1==this.score()?($(this.optionElement).addClass("correct"),""!=settings.correctChoiceText&&$(this.optionElement).find(".dki-element-content").attr("title",settings.correctChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback'\x3e"+settings.correctChoiceText+"\x3c/div\x3e"))):($(this.optionElement).addClass("incorrect"),""!=settings.incorrectChoiceText&&$(this.optionElement).find(".dki-element-content").attr("title",settings.incorrectChoiceText).append($("\x3cdiv class\x3d'sr-only sr-feedback'\x3e"+
settings.incorrectChoiceText+"\x3c/div\x3e")))};this.reset=function(){$(this.optionElement).data("dropData",null);$(this.optionElement).removeClass("correct");$(this.optionElement).removeClass("incorrect");$(this.optionElement).removeAttr("tabIndex").removeAttr("title").find(".sr-only.sr-feedback").remove();this.enabled(!0)};this.start=function(){}};
DKI.TestQuestion.ImageMapOption=function(a){this.mapEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper .dki-element-content");this.test=a;return this};
DKI.TestQuestion.ImageMapOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.mapEl.ImageMap("enterReview",!0,!a,!0)},start:function(){},score:function(){return this.mapEl.data("dki.ImageMap").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.mapEl.ImageMap(a?"enable":"disable")},reset:function(){this.mapEl.ImageMap("reset");this.enabled(!0)}};
DKI.TestQuestion.ScenarioOption=function(a){this.scenarioEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.ScenarioOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.scenarioEl.Scenario("enterReview",!0,!a)},start:function(){},score:function(){return this.scenarioEl.data("dki.Scenario").getScore()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.scenarioEl.Scenario(a?"enable":"disable")},reset:function(){this.scenarioEl.Scenario("reset")}};
DKI.TestQuestion.MatchingQuestionOption=function(a){this.matchEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.MatchingQuestionOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.matchEl.MatchingQuestion("enterReview",!0,!a)},start:function(){},score:function(){return this.matchEl.data("dki.MatchingQuestion").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.matchEl.MatchingQuestion(a?"enable":"disable")},reset:function(){this.matchEl.MatchingQuestion("reset");this.enabled(!0)}};
DKI.TestQuestion.SequencingQuestionOption=function(a){this.sequenceEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.SequencingQuestionOption.prototype={showCorrect:function(a){(this.test.isSinglePage||this.test.isPracticeQuestion)&&this.sequenceEl.SequencingQuestion("enterReview",!0,!a)},start:function(){},score:function(){return this.sequenceEl.data("dki.SequencingQuestion").score()},value:function(){return""},correctResponse:function(){},enabled:function(a){this.sequenceEl.SequencingQuestion(a?"enable":"disable")},reset:function(){this.sequenceEl.SequencingQuestion("reset");this.enabled(!0)}};
DKI.TestQuestion.captureQuestion={init:function(a){a.captureEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper");var b=function(){return{review:a.isPracticeQuestion,retake:!a.inReview&&a.isPracticeQuestion&&a.question.show_try_again&&a.numAttempts<a.question.attempts,next:function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)}}};$(document).one(DKI.ContentPage.events.loadFinished,function(){a.captureEl.off(tryMe.EVENT.RESTART_BUTTON+".dkiTest").on(tryMe.EVENT.RESTART_BUTTON+
".dkiTest",function(){a.numAttempts+=1;a.captureEl.capture("setOption",["buttons",b()])});a.captureEl.capture("setOption",["buttons",b()]);$(document).one(DKI.Events.TestQuestion.nextClicked+" "+DKI.Events.TestQuestion.forceEnd,function(){a.captureEl.capture("cleanup")});a.captureEl.capture("setOption",["showCorrectAnswers",a.canShowCorrectAnswers()&&("pre"==a.prePost&&a.behaviour.reviewPreAnswers||"post"==a.prePost&&a.behaviour.reviewPostAnswers)]);var d=a.canShowFeedback();a.captureEl.capture("setOption",
["showFeedback",d]);a.captureEl.off(testMe.EVENT.COMPLETE+".dkiTest").on(testMe.EVENT.COMPLETE+".dkiTest",function(b,d){a.inReview||a.submitted||a.submitQuestion(d.testMe.getScore())});d&&(d=a.question.parameters.feedback,a.captureEl.capture("setOption",["feedback",{correct:d.correct.useDefault?contentApi.getDefaultFeedbackText("correct"):d.correct.text,incorrect:d.incorrect.useDefault?contentApi.getDefaultFeedbackText("incorrect"):d.incorrect.text}]))})},onShowReview:function(a){var b=this;this.captureEl.css({opacity:0,
transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.question.timedOut&&b.captureEl.capture("setOption",["overrideScore",0]);b.captureEl.capture("import",[b.question.data]);b.captureEl.capture("enterReview");b.captureEl.css({opacity:1,transition:"opacity 150ms linear"});a()})},calculate:function(){return this.captureEl.capture("getScore")},getData:function(){return this.captureEl.capture("export")},getOptions:function(){return[]},getOptionFeedback:function(){return""},
getCorrectCount:function(){return 0},hasSelection:function(){return!0},getBodyText:function(){var a=this.captureEl.find("#introductionText").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.imageMapQuestion={init:function(a){a.mapEl=$(a.pageContainer).find("#"+a.question.options[0].elementId+"_wrapper .dki-element-content")},onShowReview:function(a){var b=this;this.mapEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.mapEl.ImageMap("import",b.question.data);a();b.mapEl.ImageMap("enterReview",[b.canShowCorrectAnswers()&&("pre"==b.prePost&&b.behaviour.reviewPreAnswers||"post"==b.prePost&&b.behaviour.reviewPostAnswers),!0],
!0,!0);b.mapEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(){return this.mapEl.data("dki.ImageMap").score()},getData:function(){return this.mapEl.data("dki.ImageMap").export()},getOptions:function(){return[new DKI.TestQuestion.ImageMapOption(this)]},showInlineFeedback:function(){this.mapEl.ImageMap("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.mapEl.data("dki.ImageMap").hasInlineFeedback()},
getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return this.mapEl.data("dki.ImageMap").hasSelection()},getBodyText:function(){var a=this.mapEl.find(".preamble_content").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.scenarioQuestion={init:function(a){a.scenarioEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);$(document).one(DKI.ContentPage.events.loadFinished,function(){a.scenarioEl.on("scenario.end",function(){a.inReview||a.showDefaultSubmit()})})},onShowReview:function(a){var b=this;this.scenarioEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.scenarioEl.Scenario("import",b.question.data);a();b.scenarioEl.Scenario("enterReview",
[b.canShowCorrectAnswers()&&("pre"==b.prePost&&b.behaviour.reviewPreAnswers||"post"==b.prePost&&b.behaviour.reviewPostAnswers),!0]);b.scenarioEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(){return this.scenarioEl.data("dki.Scenario").getScore()},getData:function(){return this.scenarioEl.data("dki.Scenario").export()},getOptions:function(){return[new DKI.TestQuestion.ScenarioOption(this)]},showInlineFeedback:function(){this.scenarioEl.Scenario("showInlineFeedback")},getOptionFeedback:function(){return""},
getCorrectCount:function(){return 0},hasSelection:function(){return!0},getBodyText:function(){var a=this.scenarioEl.find(".preamble_content").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.matchingQuestion={init:function(a){a.matchEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.matchEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.matchEl.MatchingQuestion("import",b.question.data);a();b.matchEl.MatchingQuestion("enterReview",[b.canShowCorrectAnswers()&&("pre"==b.prePost&&b.behaviour.reviewPreAnswers||"post"==b.prePost&&b.behaviour.reviewPostAnswers)]);
b.matchEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.matchEl.data("dki.MatchingQuestion").score(!1,!a)},getData:function(){return this.matchEl.data("dki.MatchingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.MatchingQuestionOption(this)]},showInlineFeedback:function(){this.matchEl.MatchingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.matchEl.data("dki.MatchingQuestion").hasInlineFeedback()},
getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return this.matchEl.data("dki.MatchingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){var a=this.matchEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.sequencingQuestion={init:function(a){a.sequenceEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId)},onShowReview:function(a){var b=this;this.sequenceEl.css({opacity:0,transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.sequenceEl.SequencingQuestion("import",b.question.data);a();b.sequenceEl.SequencingQuestion("enterReview",[b.canShowCorrectAnswers()&&("pre"==b.prePost&&b.behaviour.reviewPreAnswers||"post"==b.prePost&&b.behaviour.reviewPostAnswers)]);
b.sequenceEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.sequenceEl.data("dki.SequencingQuestion").score(!1,!a)},getData:function(){return this.sequenceEl.data("dki.SequencingQuestion").export()},getOptions:function(){return[new DKI.TestQuestion.SequencingQuestionOption(this)]},showInlineFeedback:function(){this.sequenceEl.SequencingQuestion("showInlineFeedback",function(){$(document).trigger(DKI.Events.TestQuestion.nextClicked)},!this.inReview)},hasInlineFeedback:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasInlineFeedback()},
getOptionFeedback:function(){return""},getCorrectCount:function(){return 0},hasSelection:function(){return this.sequenceEl.data("dki.SequencingQuestion").hasSelection()},getFeedbackConfig:function(){return this.question.parameters.feedback},getBodyText:function(){var a=this.sequenceEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};
DKI.TestQuestion.MultipleChoiceQuestionWidget={init:function(a){requirejs(["questionElement"],function(){a.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);setTimeout(function(){a.questionEl.data("dki.MultipleChoiceQuestion").setTestConfig({attempts:a.question.attempts,allowInlineFeedback:!1,showCorrectAtEnd:!1})},10)})},onShowReview:function(a){this.questionEl=$(this.pageContainer).find("#content_"+this.question.options[0].elementId);var b=this;this.questionEl.css({opacity:0,
transition:""});$(document).one(DKI.ContentPage.events.loadFinished,function(){b.questionEl.data("dki.MultipleChoiceQuestion").import(b.question.data);a();b.canShowCorrectAnswers()&&(b.questionEl.data("dki.MultipleChoiceQuestion").showGivenAnswers(),b.questionEl.data("dki.MultipleChoiceQuestion").showCorrectAnswers());b.questionEl.css({opacity:1,transition:"opacity 150ms linear"})})},calculate:function(a){return this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!1,!a,!0)},getData:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").export()},
getOptions:function(){return[new DKI.TestQuestion.MultipleChoiceQuestionWidgetOption(this)]},showInlineFeedback:function(){this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!0,!0)},hasInlineFeedback:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").hasInlineFeedback()},getOptionFeedback:function(){var a=this,b=this.questionEl.data("dki.MultipleChoiceQuestion").getSelectedOptions(),d="";$.each(b,function(){if(""!=this.parameters.config.feedback){var b=this.parameters.config.feedback.replace(/&quot;/g,
'"').replace(/&gt;/g,"\x3e").replace(/&lt;/g,"\x3c").replace(/&amp;/g,"\x26"),h=a.questionEl.find(".dki-authoring-element-element[data-id\x3d"+this.id+"]");d+="\x3cdiv class\x3d'optionFeedbackWrapper'\x3e";d+="\x3cspan class\x3d'optionFeedbackNumbering'\x3e";d+=$(".numbering",h).text();d+="\x3c/span\x3e";d+="\x3cspan class\x3d'optionFeedbackContent'\x3e";d+=b;d+="\x3c/span\x3e";d+="\x3c/div\x3e"}});return d},getCorrectCount:function(){return 0},hasSelection:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").hasSelection()},
getBodyText:function(){var a=this.questionEl.find(".question-description").text();""==a&&(a=$(".dki-questionBody-element .dki-element-content",this.pageContainer).text());return a}};DKI.TestQuestion.MultipleChoiceQuestionWidgetOption=function(a){this.questionEl=$(a.pageContainer).find("#content_"+a.question.options[0].elementId);this.test=a;return this};
DKI.TestQuestion.MultipleChoiceQuestionWidgetOption.prototype={showCorrect:function(a){if(this.test.isSinglePage||this.test.isPracticeQuestion)this.questionEl.data("dki.MultipleChoiceQuestion").showGivenAnswers(),a&&this.questionEl.data("dki.MultipleChoiceQuestion").showCorrectAnswers()},start:function(){},score:function(){return this.questionEl.data("dki.MultipleChoiceQuestion").scoreQuestion(!1,!0)},value:function(){return""},correctResponse:function(){},enabled:function(a){a?this.questionEl.data("dki.MultipleChoiceQuestion").enableInputs():
this.questionEl.data("dki.MultipleChoiceQuestion").disableInputs()},reset:function(){this.questionEl.data("dki.MultipleChoiceQuestion").reset();this.enabled(!0)}};