/*! -- File: testMe.js ( Input 0 ) -- */
var testMe=function(a){a=a||{};a.TOOLTIP_THEME=a.TOOLTIP_THEME||"tooltipster-capture";tryMe.call(this,a);this.options=$.extend(JSON.parse(JSON.stringify(testMe.DEFAULTS)),this.options);this.generateAssessments();this.$elements.sideContainer.addClass(this.options.mode.charAt(0).toLowerCase()+this.options.mode.slice(1));this.options.reviewData?(this.import(this.options.reviewData),delete this.options.reviewData,this.enterReview()):this.$elements.sectionInfo.find("#section-1").data("section-introduction")?
this.$elements.startScreen.find("button").trigger("click"):this.$elements.startScreen.show();return this};testMe.DEFAULTS={mode:"Practice",buttons:{next:!1,review:!0,retake:!0},showScore:!0,showFeedback:!0,showCorrectAnswers:!0,feedback:{correct:"",incorrect:""},overrideScore:!1,iconPath:""};testMe.EVENT={ATTEMPT:"testMe.attempt",CORRECT:"testMe.correct",INCORRECT:"testMe.incorrect",COMPLETE:"testMe.complete"};
testMe.prototype=$.extend(Object.create(tryMe.prototype),{sideContainerScrollParentSelector:".panel .list-group",resizeSideContainer:function(){this.moveHotspot();this.repositionReviewOverlayItems()},setElements:function(){tryMe.prototype.setElements.call(this);this.$elements.carouselContainer=this.$container.find("#testMeContainer");this.$elements.dragOverlay=this.$container.find("#testMeDragOverlay");this.$elements.sideContainer=this.$container.find("#testMeSideContainer");this.$elements.infoScreen=
this.$container.find("#testMeInfoScreen");this.$elements.reviewOverlay=this.$container.find("#testMeReviewOverlay");this.$elements.showReview=this.$container.find("#showReviewToggle");this.$elements.showInfo=this.$container.find("#sceneInfo");this.$elements.introductionOverlay=this.$container.find("#introductionOverlay");this.$elements.introductionTextContainer=this.$container.find("#introductionTextContainer");this.$elements.introductionText=this.$container.find("#introductionText");this.$elements.introductionContainerPlayButton=
this.$container.find("#introductionContainerPlayButton")},eventListeners:function(){var a=this;tryMe.prototype.eventListeners.call(this);this.$container.on(tryMe.EVENT.STEP_CHANGED,function(){var b=a.getCurrentStepObj();a.state.currentEventType===tryMe.CAPTURE_EVENT.STOP||b.hasHotspot()||a.inReview||1==a.assessment.steps[a.state.overallStep-1].passed||a.showPopupForStep(b);a.inReview?a.loadReviewForStep(a.state.overallStep):1==a.getCurrentStepFromOverallStep(a.state.overallStep)&&a.$elements.showInfo.removeClass("active").trigger("click");
b=a.$elements.sectionInfo.find("#section-"+a.getCurrentSection());a.$elements.showInfo[b[0]&&b.data("section-introduction")?"show":"hide"]()});this.$elements.showReview.on("click",function(){$(this).toggleClass("correct");$(this).find(".fa").removeClass("fa-check fa-times").addClass($(this).hasClass("correct")?"fa-times":"fa-check");a.reviewControl[$(this).hasClass("correct")?"correct":"incorrect"]()});this.$container.on(tryMe.EVENT.RESTART_BUTTON,function(){a.cleanup()});this.$elements.showInfo.on("click",
function(){var b=a.$elements.sectionInfo.find("#section-"+a.getCurrentSectionFromOverallStep(a.state.overallStep));b.data("section-introduction")&&($(this).toggleClass("active"),$(this).hasClass("active")?(b=a.$elements.sectionInfo.find("#section-"+a.getCurrentSectionFromOverallStep(a.state.overallStep)),a.showIntroSummaryPane(b.data("section-introduction"))):a.closeIntroSummaryPane());return!1});this.$elements.introductionContainerPlayButton.on("click",function(){a.$elements.showInfo.trigger("click")})},
initializeHandlers:function(){tryMe.prototype.initializeHandlers.call(this);var a=this;this.$elements.carousel.on("mouseup touchend",".item.active",function(b){if(a.state.currentEventType==tryMe.CAPTURE_EVENT.DRAG_START||a.state.currentEventType==tryMe.CAPTURE_EVENT.DRAG_FINISH)a.resetDrag(!1);else if(a.state.currentEventType!=tryMe.CAPTURE_EVENT.TYPED)return!1})},getNextStep:function(){for(var a=this.state.overallStep+1;(this.getEventTypeForStep(a)===tryMe.CAPTURE_EVENT.STOP||this.getEventTypeForStep(a)===
tryMe.CAPTURE_EVENT.EXPLANATION)&&a!==this.state.steps.length;)++a;return a},getAssessment:function(a){a=a||this.state.overallStep;return this.assessment.steps[a-1]},sidePanelItemClicked:function(a){if(!this.inReview)return!1;tryMe.prototype.sidePanelItemClicked.call(this,a)},toggleItemCircle:function(a,b){!this.inReview&&0<this.state.overallStep?tryMe.prototype.toggleItemCircle.call(this,a,b):(a.find(".step-checkmark").show(),a.find(".step-number").hide())},tryNext:function(a,b){var c=this;return this.state.currentEventType==
tryMe.CAPTURE_EVENT.DRAG_FINISH&&"click"==b.type&&a?tryMe.prototype.tryNext.call(this,a,b):{then:function(d,e){var f=c.assessment.steps[c.state.overallStep-1];f.assess(a,b)?(c.$container.trigger(testMe.EVENT[f.passed?"CORRECT":"INCORRECT"],{testMe:c,assessment:f}),f.goNext(),d()):(c.$container.trigger(testMe.EVENT.ATTEMPT,{testMe:c,assessment:f}),e())}}},createStepAssessment:function(a){var b=this.getCurrentStepFromOverallStep(a);a=this.getCurrentSectionFromOverallStep(a);listItem=this.$elements.sideContainer.find(".list-group .row[data-step-count\x3d'"+
b+"'][data-section-count\x3d'"+a+"']");return testMe.stepAssessmentFactory.create(this,listItem)},loadScores:function(){var a=this.getScore();if(this.options.showScore){var b=this.$elements.infoScreen.find(".radial").show().RadialGauge({asPercent:!0,parentSelector:".radialContainer",width:200}),b=b.add(this.$elements.sideContainer.find(".row.score").show().find(".radial").RadialGauge({asPercent:!0,parentSelector:".row.score",width:54}));b.RadialGauge("setRotation",this.getScore());b.RadialGauge("resize")}else this.$elements.infoScreen.find(".radial").hide(),
this.$elements.sideContainer.find(".row.score").hide();return a},getTestingFeedback:function(){if(!this.options.showFeedback)return"";var a=100==this.getScore()?"correct":"incorrect";if(this.options.feedback[a])return"\x3cdiv class\x3d'feedback'\x3e"+this.options.feedback[a]+"\x3c/div\x3e"},onEndReached:function(){this.toggleRestartAnimation()},toggleRestartAnimation:function(){this.$elements.infoScreen.find(".feedback").remove();var a=this.getTestingFeedback();a&&this.$elements.infoScreen.find(".infoButtons").before(a);
tryMe.prototype.toggleRestartAnimation.call(this,!0);a=this.loadScores();this.toggleInfoButtons();this.inReview||this.$container.trigger(testMe.EVENT.COMPLETE,{testMe:this,score:a})},toggleInfoButtons:function(){var a=this,b=this.$elements.infoScreen.find(".btn");b.off("click").css("display","none");$.each(this.options.buttons,function(a,d){a=b.filter("."+a);if(a[0]&&d&&(a.css("display",""),"function"==typeof d))a.on("click",d)});this.$elements.infoScreen.find(".btn.review").on("click.default",function(){a.closeInfoScreen();
a.enterReview()});this.$elements.infoScreen.find(".btn.retake").on("click.default",function(){a.$container.trigger(tryMe.EVENT.RESTART_BUTTON,a);a.nextStep();a.$container.trigger(tryMe.EVENT.START,a)})},showIntroSummaryPane:function(a){if(a){this.$elements.introductionText.html(a);a=this.$elements.introductionText.height();var b=this.$elements.introductionTextContainer.height();if(a>b){this.$elements.introductionTextContainer.addClass("introduction-text-flex-start");this.$elements.introductionTextContainer.scrollTop(0);
var c=this;this.$elements.introductionTextContainer.on("scroll",function(){$(this).scrollTop()+$(this).innerHeight()>=$(this)[0].scrollHeight&&c.$elements.introductionContainerPlayButton.prop("disabled",!1)})}else this.$elements.introductionTextContainer.removeClass("introduction-text-flex-start");this.$elements.introductionOverlay.addClass("justify-content-center");this.$elements.introductionOverlay.removeClass("hide-introduction")}},closeIntroSummaryPane:function(){this.$elements.introductionOverlay.addClass("hide-introduction");
this.$elements.introductionOverlay.removeClass("justify-content-center")},repositionReviewOverlayItems:function(){this.inReview&&this.reviewControl.reposition()},generateAssessments:function(){var a=this;this.assessment={steps:this.state.steps.reduce(function(b,c,d){c.eventType==tryMe.CAPTURE_EVENT.STOP&&d==a.state.steps.length-1||b.push(a.createStepAssessment(d+1));return b},[])}},cleanup:function(){this.generateAssessments();var a=this.$elements.sideContainer.find(".row").removeClass("pass fail");
a.find(".progression span").removeClass("try on");a.find(".step-checkmark .fa").removeClass("fa-times fa-check");this.$elements.sideContainer.find(".row.score").hide();this.reviewControl&&this.reviewControl.clearHint();this.hideHintText();this.$elements.sideContainer.find(".row.tooltipstered").tooltipster("destroy")},showPopupForStep:function(a){var b=this.$elements.sideContainer.find(".active"),c=b.find(".col-instructions").clone().addClass("testMeFeedback");c.prepend("\x3ch4 title\x3d'"+a.instructionalText+
"'\x3e\x3cspan\x3e"+a.instructionalText+"\x3c/span\x3e\x3c/h4\x3e").addClass("testMePopout");c.find(".continue p").addClass("content");c.find(".btn").addClass("btn-primary btn-continue").removeClass("btn-step-continue");this.showTooltip(b,{content:c,position:"right",trigger:"custom",arrow:!0,functionReady:function(a,c){$(c.tooltip).find(".continue").css("opacity",1).on("click",".btn-continue",function(a){b.find(".btn-step-continue").trigger("click")})}})},updateList:function(){var a=this;tryMe.prototype.updateList.call(this,
function(b){var c=b.data("step-count"),f=b.data("section-count"),c=a.getEventTypeForStep(a.getOverallStepFromSectionAndStep(f,c));c!==tryMe.CAPTURE_EVENT.STOP&&c!==tryMe.CAPTURE_EVENT.EXPLANATION||b.css("display","none")});var b=this.getCurrentSectionFromOverallStep(this.state.overallStep),c=this.$elements.sideContainer.find(".row.section").removeClass("current");c.find("span").css("background-image","url('"+this.options.iconPath+"/scene.png')");c.filter("*[data-id\x3d'"+b+"']").addClass("current").find("span").css("background-image",
"url('"+this.options.iconPath+"/scene_selected.png')")},enterReview:function(){this.inReview=!0;this.closeIntroSummaryPane();this.$elements.carouselContainer.addClass("inReview");var a=this.$elements.sideContainer.find(".row.pass, .row.fail").attr("style","cursor : pointer !important;");this.goToStep(a.first())},exitReview:function(){this.$elements.carouselContainer.removeClass("inReview");this.$elements.sideContainer.find(".row.pass, .row.fail").css("style","");this.$elements.showReview.css("display",
"");this.inReview=!1},loadReviewForStep:function(a){var b=this.getAssessment(a);b&&(this.reviewControl&&this.reviewControl.clearHint(),a=this.getCurrentStepObj(),this.reviewControl=new (testMe.reviewControl[a.eventType]||testMe.reviewControl[tryMe.CAPTURE_EVENT.CLICK])(this,b,a,this.state.overallStep),this.reviewControl.toggleReviewButton(),this.$elements.showReview.trigger("click"))},getNextAssessmentIdx:function(){for(var a=!1,b=this.state.overallStep;b<this.assessment.steps.length;b++)if(this.assessment.steps[b]&&
this.getEventTypeForStep(b+1)!==tryMe.CAPTURE_EVENT.STOP&&this.getEventTypeForStep(b+1)!==tryMe.CAPTURE_EVENT.EXPLANATION){a=b;break}return a},getScore:function(){var a=this;if(!1!==this.options.overrideScore&&!isNaN(this.options.overrideScore))return this.options.overrideScore;var b=current=0;$.each(this.assessment.steps,function(c,d){d&&a.getEventTypeForStep(c+1)!==tryMe.CAPTURE_EVENT.STOP&&a.getEventTypeForStep(c+1)!==tryMe.CAPTURE_EVENT.EXPLANATION&&(b+=this.maxTries,current+=this.getScore())});
return Math.round(current/b*100)},export:function(){var a=[];$.each(this.assessment.steps,function(b,c){a.push(this.export())});return a},import:function(a){var b=this;this.assessment.steps=[];$.each(a,function(a,d){d=JSON.parse(JSON.stringify(this));var e=b.createStepAssessment(a+1);b.assessment.steps.push(e);e.import(d);b.state.completedSteps.push(a)});this.loadScores();return this},setOption:function(a,b){this.options[a]=b},destroy:function(){tryMe.prototype.destroy.call(this);this.$container.off(tryMe.EVENT.STEP_CHANGED);
this.$container.off(tryMe.EVENT.RESTART_BUTTON)},getStepFactory:function(){this.stepFactory||(this.stepFactory=new testMe.StepFactory);return this.stepFactory}});testMe.prototype.constructor=testMe;testMe.stepAssessmentFactory={create:function(a,b){return new testMe.stepAssessment[a.options.mode](a,b)}};testMe.stepAssessment=function(a,b){this.$=b;this.testMe=a;this.passed=!1;this.tries=[];return this};
testMe.stepAssessment.prototype={assess:function(a,b){!this.passed&&this.tries.length<this.maxTries&&this.tries.push(this.createTryFromData(b));this.tries.length<=this.maxTries&&a&&!this.final&&(this.passed=!0);this.doForAssess(this.passed||a);if(this.passed||this.tries.length>=this.maxTries)this.onFinalMark(),this.final=!0;return a},createTryFromData:function(a){var b={type:a.type};switch(this.testMe.state.currentEventType){case tryMe.CAPTURE_EVENT.TYPED:$.extend(b,{value:this.testMe.$elements.hotspot.find("input").val(),
type:"key"});break;case tryMe.CAPTURE_EVENT.SELECT:$.extend(b,{value:this.testMe.$elements.hotspot.find("select").val(),type:"select"});break;default:var c=1/this.testMe.getScale();$.extend(b,{x:a.offsetX*c,y:a.offsetY*c})}return b},getScore:function(){return this.passed?this.maxTries-(this.tries.length-1):0},doForAssess:function(){return this},onFinalMark:function(){this.$.addClass(this.passed?"pass":"fail").find(".step-checkmark .fa").addClass(this.passed?"fa-check":"fa-times");return!0},goNext:function(){this.$.hasClass("tooltipstered")&&
this.$.tooltipster("destroy")},getFeedbackTries:function(){return this.tries.slice(0,-1)},export:function(){return{passed:this.passed,tries:this.tries}},renderAssessment:function(){this.doForAssess(!0).onFinalMark();this.$.find(".step-number").hide();this.$.find(".step-checkmark").show()},import:function(a){this.passed=a.passed;this.tries=a.tries;this.renderAssessment();return this}};testMe.stepAssessment.Practice=function(a,b){testMe.stepAssessment.apply(this,arguments);this.maxTries=3;this.setMenuState()};
testMe.stepAssessment.Practice.prototype=$.extend(Object.create(testMe.stepAssessment.prototype),{setMenuState:function(){for(var a=this.$.find(".progression \x3e span"),b=0;b<this.tries.length;b++)$(a.get(b)).addClass("try").removeClass("on")},setNextOn:function(){var a=this.$.find(".progression \x3e span");this.tries.length<a.length&&$(a.get(this.tries.length)).addClass("on")},doForAssess:function(a){this.setMenuState();if(!a){var b=this;this.showFeedbackForTry(function(){b.setNextOn()})}return this},
showFeedbackForTry:function(a){this.$.siblings(".tooltipstered").tooltipster("destroy");var b=this.testMe.getCurrentStepObj(),c=this,d={position:"right",trigger:"custom",arrow:!0,theme:"tooltipster-capture",functionReady:function(b,d){c.testMe.hideHintText();$(d.tooltip).on("click",".continue",function(b,d){c.$.tooltipster("hide");b=c.testMe.getCurrentStepObj();b.hasHotspot()||c.testMe.showPopupForStep(b);(3<=c.tries.length||d)&&c.testMe.showHint();a()});$(d.tooltip).on("click",".hint",function(){$(d.tooltip).find(".continue").trigger("click",
!0)})}};d.content="\x3cdiv class\x3d'testMeFeedback'\x3e\x3ch4\x3e\x3ci class\x3d'fa fa-times label-circle'\x3e\x3c/i\x3e\x3cspan\x3e"+this.testMe.options.STRINGS.INCORRECT_ATTEMPT+"\x3c/span\x3e\x3c/h4\x3e\x3cdiv class\x3d'content'\x3e";b.testMeFeedbackText&&(d.content+="\x3cdiv\x3e\x3cspan style\x3d'font-weight:bold; color:#666;'\x3e"+this.testMe.options.STRINGS.FEEDBACK_FEEDBACK_LABEL+"\x3c/span\x3e: "+b.testMeFeedbackText+"\x3c/div\x3e");d.content=2<=this.tries.length?d.content+("\x3cdiv\x3e\x3cspan style\x3d'font-weight:bold; color:#666;'\x3e"+
this.testMe.options.STRINGS.FEEDBACK_STEP_LABEL+"\x3c/span\x3e: "+b.instructionalText+"\x3c/div\x3e\x3c/div\x3e\x3cbutton class\x3d'btn btn-primary hint'\x3e"+this.testMe.options.STRINGS.SHOW_HINT+"\x3c/button\x3e"):d.content+"\x3c/div\x3e";d.content+="\x3cbutton class\x3d'btn btn-primary continue'\x3e"+this.testMe.options.STRINGS.CONTINUE+"\x3c/button\x3e\x3c/div\x3e";this.testMe.showTooltip(this.$,d)}});
testMe.stepAssessment.Challenge=function(a,b){testMe.stepAssessment.apply(this,arguments);this.maxTries=1;this.final=!1};
testMe.stepAssessment.Challenge.prototype=$.extend(Object.create(testMe.stepAssessment.prototype),{assess:function(a,b){!this.passed&&this.tries.length<this.maxTries&&this.tries.push(this.createTryFromData(b));this.tries.length<=this.maxTries&&a&&!this.final&&(this.passed=!0);this.doForAssess(this.passed||a);if(this.passed||this.tries.length>=this.maxTries)this.onFinalMark(),this.final=!0;return this.passed||this.tries.length>=this.maxTries},getFeedbackTries:function(){return this.passed?[]:this.tries},
getScore:function(){return this.maxTries-(this.tries.length-(this.passed?1:0))}});testMe.reviewControl=function(a,b,c,d){this.testMe=a;this.assessment=b;this.step=c;this.overallStep=d;this.$=this.step.hasHotspot()?a.$elements.hotspot:this.assessment.$;return this};
testMe.reviewControl.prototype={clearHint:function(){this.testMe.$elements.reviewOverlay.find(".tooltipstered").tooltipster("destroy");this.testMe.$elements.reviewOverlay.html("");this.testMe.hideHintText();this.$.hasClass("tooltipstered")&&this.$.tooltipster("destroy");this.$.removeClass("hotspotHint")},renderNext:function(){return"\x3cdiv class\x3d'clearfix' id\x3d'testMeReviewContainer'\x3e\x3cdiv class\x3d'"+(!1!==this.testMe.getNextAssessmentIdx()?"next'\x3e"+this.testMe.options.STRINGS.NEXT:
"finish'\x3e"+this.testMe.options.STRINGS.FINISH)+"\x3c/div\x3e\x3c/div\x3e"},onNext:function(){this.testMe.goToStep(this.testMe.assessment.steps[this.testMe.getNextAssessmentIdx()].$)},onFinish:function(){this.clearHint();this.testMe.exitReview();this.testMe.toggleRestartAnimation()},toggleReviewButton:function(){var a=this.testMe.options.showCorrectAnswers||this.assessment.passed,b=1==this.assessment.tries.length&&this.assessment.passed;this.testMe.$elements.showReview[b?"removeClass":"addClass"]("correct")[b||
!a?"hide":"show"]()},reposition:function(){},correct:function(){},incorrect:function(){}};testMe.reviewControl[tryMe.CAPTURE_EVENT.CLICK]=function(a,b,c,d){testMe.reviewControl.apply(this,arguments);return this};
testMe.reviewControl[tryMe.CAPTURE_EVENT.CLICK].prototype=$.extend(Object.create(testMe.reviewControl.prototype),{reposition:function(){var a=this;this.testMe.$elements.reviewOverlay.find(".markerContainer").each(function(){var b=$(this),c=a.testMe.getElementPositionOverStep(b,a.testMe.getCarouselItemForStep(a.testMe.state.overallStep)),d=b[0].getBoundingClientRect(),e=b.find(".marker")[0].getBoundingClientRect();b.css({top:c.top-(e.height-(e.height-d.height)/2),left:c.left-d.width/2})})},incorrect:function(){this.clearHint();
var a=this;$.each(this.assessment.getFeedbackTries(),function(){$(testMe.templates.marker()).appendTo(a.testMe.$elements.reviewOverlay).data({hotspotMiny:this.y,hotspotMinx:this.x})});this.reposition();this.testMe.showTooltip($(this.testMe.$elements.reviewOverlay.children().first()),{content:testMe.templates.genericFeedback(this.step,this.assessment,this.testMe.getCurrentVisibleActiveStepWithSection(),!0)+this.renderNext()+"\x3c/div\x3e",position:"right",trigger:"custom",arrow:!0,functionReady:function(b,
c){$(c.tooltip).on("click",".next",$.proxy(a.onNext,a));$(c.tooltip).on("click",".finish",$.proxy(a.onFinish,a))}})},correct:function(){this.clearHint();this.testMe.showHint(!1,!0);var a=this;this.testMe.showTooltip(this.$,{content:testMe.templates.genericFeedback(this.step,this.assessment,this.testMe.getCurrentVisibleActiveStepWithSection())+this.renderNext()+"\x3c/div\x3e",position:"right",trigger:"custom",arrow:!0,functionReady:function(b,c){$(c.tooltip).on("click",".next",$.proxy(a.onNext,a));
$(c.tooltip).on("click",".finish",$.proxy(a.onFinish,a))}});this.$.addClass("hotspotHint")}});testMe.reviewControl[tryMe.CAPTURE_EVENT.DRAG_FINISH]=function(a,b,c,d){testMe.reviewControl.apply(this,arguments);return this};
testMe.reviewControl[tryMe.CAPTURE_EVENT.DRAG_FINISH].prototype=$.extend(Object.create(testMe.reviewControl.prototype),{reposition:function(){var a=this,b=this.testMe.getScale();this.testMe.$elements.reviewOverlay.find("\x3e*").each(function(){var c=$(this),d=a.testMe.getElementPositionOverStep(c,a.testMe.getCarouselItemForStep(a.testMe.state.overallStep));c.css({top:d.top-$(this).height()/2,left:d.left-$(this).width()/2,height:$(this).data("baseHeight")*b,width:$(this).data("baseWidth")*b})})},incorrect:function(){this.clearHint();
var a=this;this.testMe.getScale();var b=this.testMe.getCarouselItemForStep(this.overallStep);baseWidth=b.data("hotspotWidth");baseHeight=b.data("hotspotHeight");$.each(this.assessment.getFeedbackTries(),function(){var b=$("\x3cdiv/\x3e").css({border:"2px solid #A81E1E",width:a.$.width(),height:a.$.height(),position:"absolute"}).data({hotspotMiny:this.y,hotspotMinx:this.x,baseWidth:baseWidth,baseHeight:baseHeight});a.testMe.$elements.reviewOverlay.append(b)});this.reposition();this.testMe.showTooltip($(this.testMe.$elements.reviewOverlay.children().first()),
{content:testMe.templates.genericFeedback(this.step,this.assessment,this.testMe.getCurrentStepFromOverallStep(this.overallStep),!0)+this.renderNext()+"\x3c/div\x3e",position:"right",trigger:"custom",arrow:!0,functionReady:function(b,d){$(d.tooltip).on("click",".next",$.proxy(a.onNext,a));$(d.tooltip).on("click",".finish",$.proxy(a.onFinish,a))}})},correct:function(){this.clearHint.call(this);var a=this;this.testMe.showTooltip(this.$,{content:testMe.templates.genericFeedback(this.step,this.assessment,
this.testMe.getCurrentStepFromOverallStep(this.overallStep))+this.renderNext()+"\x3c/div\x3e",position:"right",trigger:"custom",arrow:!0,functionReady:function(b,c){$(c.tooltip).on("click",".next",$.proxy(a.onNext,a));$(c.tooltip).on("click",".finish",$.proxy(a.onFinish,a))}});this.testMe.$elements.hotspot.addClass("hotspotHint");this.testMe.showHint(this.overallStep-1,!0)}});testMe.reviewControl[tryMe.CAPTURE_EVENT.TYPED]=function(a,b,c,d){testMe.reviewControl.apply(this,arguments);return this};
testMe.reviewControl[tryMe.CAPTURE_EVENT.TYPED].prototype=$.extend(Object.create(testMe.reviewControl.prototype),{incorrect:function(){this.clearHint.call(this);this.testMe.$elements.showReview.hide();var a=this;this.testMe.showTooltip(this.$,{content:testMe.templates.typedFeedback(this.step,this.assessment,this.testMe.getCurrentStepFromOverallStep(this.overallStep))+this.renderNext()+"\x3c/div\x3e",position:"right",trigger:"custom",arrow:!0,functionReady:function(b,c){$(c.tooltip).on("click",".next",
$.proxy(a.onNext,a));$(c.tooltip).on("click",".finish",$.proxy(a.onFinish,a))}});this.$.addClass("hotspotHint").find("input").attr("disable",!0).val(this.step.stringTyped).blur()},toggleReviewButton:function(){this.testMe.$elements.showReview.removeClass("correct").hide()}});testMe.reviewControl[tryMe.CAPTURE_EVENT.TYPED].prototype.correct=testMe.reviewControl[tryMe.CAPTURE_EVENT.TYPED].prototype.incorrect;testMe.reviewControl[tryMe.CAPTURE_EVENT.SELECT]=testMe.reviewControl[tryMe.CAPTURE_EVENT.TYPED];
testMe.templates={feedbackHeader:function(a,b){return"\x3ch4\x3e\x3ci class\x3d'label-circle'\x3e"+a+"\x3c/i\x3e\x3cspan\x3e"+b+"\x3c/span\x3e\x3c/h4\x3e"},genericFeedback:function(a,b,c,d){return"\x3cdiv class\x3d'testMeFeedback'\x3e"+testMe.templates.feedbackHeader(c,b.testMe.options.STRINGS[d?"INCORRECT":"CORRECT"])+(a.instructionalText?"\x3cdiv class\x3d'content'\x3e"+a.instructionalText+"\x3c/div\x3e":"")},typedFeedback:function(a,b,c){a.instructionalText="";var d="\x3cdiv class\x3d'testMeFeedback'\x3e"+
testMe.templates.feedbackHeader(c,b.testMe.options.STRINGS.CORRECT)+(a.instructionalText?"\x3cdiv class\x3d'content'\x3e"+a.instructionalText+"\x3c/div\x3e":"")+"\x3cdiv class\x3d'content' style\x3d'border-bottom : 1px solid #CCC; padding-bottom:10px;'\x3e"+(b.testMe.options.showCorrectAnswers||b.passed?"\x3cspan class\x3d'line correct'\x3e\x3c/span\x3e"+a.stringTyped:"")+"\x3c/div\x3e\x3cdiv class\x3d'content'\x3e\x3ch4\x3e"+b.testMe.options.STRINGS.FEEDBACK_TYPED_YOU_TYPED+"\x3c/h4\x3e",e=b.tries;
$.each(e,function(a,c){d+="\x3cdiv style\x3d'margin-bottom:5px'\x3e\x3cspan class\x3d'line "+(e.length-1==a&&b.passed?"correct":"incorrect")+"'\x3e\x3c/span\x3e\x3cspan\x3e"+this.value+"\x3c/span\x3e\x3c/div\x3e"});return d+"\x3c/div\x3e"},marker:function(){return"\x3cdiv class\x3d'markerContainer' style\x3d' position:absolute'\x3e\x3ci class\x3d'marker pin fa fa-times'\x3e\x3c/i\x3e\x3cdiv class\x3d'markerPulsar pin'\x3e\x3c/div\x3e\x3c/div\x3e"}};testMe.StepFactory=function(){};
testMe.StepFactory.prototype=$.extend(Object.create(tryMe.StepFactory.prototype),{findClass:function(a){return testMe[a]||tryMe.StepFactory.prototype.findClass(a)}});testMe.ClickStep=function(){tryMe.ClickStep.apply(this,arguments)};testMe.ClickStep.prototype=$.extend(Object.create(tryMe.ClickStep.prototype),{bindHandlers:function(){var a=this;tryMe.ClickStep.prototype.bindHandlers.call(this);this.subscribe("mouseup touchend",".item.active",function(b){a.interacted(!1,b);return!1})}});
testMe.DragStart=function(){tryMe.DragStart.apply(this,arguments)};testMe.DragStart.prototype=$.extend(Object.create(tryMe.DragStart.prototype),{bindHandlers:function(){var a=this;tryMe.DragStart.prototype.bindHandlers.call(this);this.subscribe("mousedown touchstart",".item.active",function(b){a.interacted(!1,b);var c=a.player.getCurrentStepObj();c.eventType===tryMe.CAPTURE_EVENT.DRAG_FINISH&&("Challenge"===a.player.options.mode?c.showDragProxy(b):a.player.resetDrag(!0));return!1})}});