/*! -- File: tryMe.js ( Input 0 ) -- */
var tryMe=function(a){this.options=$.extend({},tryMe.DEFAULTS,a);this.state={currentStepValidated:!1,dragging:!1,fullscreen:!1,overallStep:0,totalClicks:0,totalTime:0,prevClicks:0,prevTime:0,restartButtonEnabled:!1,hintButtonEnabled:!1,steps:[],completedSteps:[]};return this.init()};tryMe.CONST=Object.freeze({ENTER_BUTTON:13,TAB_BUTTON:9});
tryMe.DEFAULTS={FADE_TIME:500,FADE_MULTIPLIER:5,MIN_HINT_TEXT_WIDTH:150,HINT_TEXT_MARGIN:10,TOOLTIP_THEME:"tooltipster-capture",mobile:!1,scale:function(){return 1},STRINGS:{INCORRECT_ATTEMPT:"Incorrect Attempt",CORRECT:"Correct Answer",INCORRECT:"Incorrect Answer",CONTINUE:"Continue",NEXT:"Next",FINISH:"Finish",SHOW_HINT:"Show Hint",FEEDBACK_FEEDBACK_LABEL:"Feedback",FEEDBACK_STEP_LABEL:"Step",FEEDBACK_TYPED_YOU_TYPED:"You Typed",RESTART_TEXT:"Steps completed"}};
tryMe.EVENT={START:"tryMe.play",RESTART:"tryMe.pause",STEP_CHANGED:"tryMe.stepChanged",STEP_FINISHED:"tryMe.stepFinished",HINT:"tryMe.showHint",ASSESSMENT_CHANGED:"tryMe.assessmentChanged",RESTART_BUTTON:"tryMe.restart"};tryMe.CAPTURE_EVENT={TYPED:"TYPED",DRAG_START:"START_MOUSE_DRAGGED",DRAG_FINISH:"FINISH_MOUSE_DRAGGED",CLICK:"MOUSE_CLICKED",BUTTON_PRESSED:"BUTTON_PRESSED",KEY_COMBO:"KEY_COMBINATION",SPECIAL_KEY:"SPECIAL_KEY",EXPLANATION:"EXPLANATION",SELECT:"SELECT",STOP:"STOP_CAPTURE"};
tryMe.prototype={sideContainerScrollParentSelector:".panel",init:function(){this.$container=this.options.container;for(var a=0;a<this.options.sections.length;a++)for(var b=0;b<this.options.sections[a].steps.length;b++)this.state.steps.push(this.getStepFactory().createStep(this.options.sections[a].steps[b],this));this.setElements();$.each($("img.unloaded"),function(){$(this).attr("src",$(this).data("src"));$(this).removeClass("unloaded")});this.$elements.carousel.find(".item:first").addClass("active");
this.resizeSideContainer();this.updateList();this.state.resizeInterval=setInterval($.proxy(this.resizeSideContainer,this),1E3);this.$elements.dragOverlay.hide();this.initializeHandlers();this.eventListeners();this.correctSideContainerStepCount();this.state.assessTimer=setInterval($.proxy(function(){this.state.totalTime+=1},this),1E3);return this},setElements:function(){this.$elements={sectionInfo:this.$container.find("#sectionInfo"),carousel:this.$container.find("#softwareSimCarousel"),carouselContainer:this.$container.find("#tryMeContainer"),
hotspot:this.$container.find(".targetHotspot"),dragOverlay:this.$container.find("#tryMeDragOverlay"),hintButton:this.$container.find("#hintButton"),sideContainer:this.$container.find("#tryMeSideContainer"),infoScreen:this.$container.find("#tryMeInfoScreen"),startScreen:this.$container.find("#startScreen"),continueScreen:this.$container.find(".continue"),tooltipTemplate:this.$container.find("#tooltipTemplate")}},eventListeners:function(){var a=this;this.$container.on(tryMe.EVENT.RESTART_BUTTON,function(){a.state.restartButtonEnabled=
!1;a.state.overallStep=0;a.$elements.sideContainer.find(".active .arrow-hint").removeClass("arrow-hint-active");a.toggleRestartButton()})},initializeHandlers:function(){var a=this;$(window).on("resize."+this.$container.attr("id"),function(){a.resizeSideContainer();a.state.currentEventType==tryMe.CAPTURE_EVENT.TYPED&&a.toggleTypingTooltip(!0)});this.$elements.carousel.find("img").on("dragstart",function(a){a.preventDefault()});this.$elements.startScreen.find(".btn").on("click",function(){a.nextStep();
a.$container.trigger(tryMe.EVENT.START,a)});this.$elements.carouselContainer.find(".try-me-restart-btn").on("click",function(){$(this).trigger("blur");a.$container.trigger(tryMe.EVENT.RESTART_BUTTON,a);a.nextStep();a.$container.trigger(tryMe.EVENT.START,a)});this.$container.find("#fullScreen").on("click",function(){a.toggleFullscreen()});this.$elements.hintButton.on("click",function(){a.showHint()});this.$elements.sideContainer.find("li").on("click",function(){a.sidePanelItemClicked($(this))})},sidePanelItemClicked:function(a){this.goToStep(a)},
correctSideContainerStepCount:function(){for(var a=$("#testMeSideContainer \x3e div \x3e .list-group").children().get(),b=1,c=0;c<a.length;c++)"DIV"!==a[c].tagName?"none"!==$(a[c]).css("display")&&$(a[c]).find(".step-number").text(b++):b=1},getCurrentSectionFromOverallStep:function(a){var b=-1,c=0;this.$elements.sectionInfo.find("\x3e*").each(function(d,e){e=$(this).data("section-size")||0;if(e>=a-c)return b=d+1,!1;c+=e});return b},getCurrentStepFromOverallStep:function(a){var b=-1,c=0;this.$elements.sectionInfo.find("\x3e*").each(function(){var d=
$(this).data("section-size")||0;if(d>=a-c)return b=a-c,!1;c+=d});return b},getCurrentVisibleActiveStepWithSection:function(){for(var a=$("#testMeSideContainer \x3e div \x3e .list-group").children().get(),b=0,c=0;c<a.length;c++)if("DIV"===a[c].tagName)b=0;else if("none"!==$(a[c]).css("display")&&(b++,a[c].classList.contains("active")))return b},getOverallStepFromSectionAndStep:function(a,b){if(1==a)return b;var c=0,d;for(d=1;d<a;d++){var e=this.$elements.sectionInfo.find("#section-"+d).data("section-size");
null!=e&&(c+=e)}return c+b},getCarouselItemForStep:function(a){var b=this.getCurrentStepFromOverallStep(a);a=this.getCurrentSectionFromOverallStep(a);return this.$elements.carousel.find("[data-step-count\x3d'"+b+"'][data-section-count\x3d'"+a+"']")},getHotspotForCurrentStep:function(a){var b=[],c;for(c in arguments)b.push(arguments[c]);return this.getHotspotForStep.apply(this,[this.state.overallStep].concat(b))},getHotspotForStep:function(a,b){a=this.getCarouselItemForStep(a);var c=b?1:this.getScale();
b=a.data("hotspotWidth")*c;var d=a.data("hotspotHeight")*c;a=this.getElementPositionOverStep(a,a,c);return{left:a.left,top:a.top,width:b,height:d}},getElementPositionOverStep:function(a,b,c){if(b[0]){var d="none"===b.css("display")?b.parent():b;c=c||this.getScale();var e=a.data("hotspotMinx")*c,f=a.data("hotspotMiny")*c;a=b.find("img")[0].width;d.width()>a&&(e=parseFloat(e,10)+(d.width()-a)/2)}return{left:e||0,top:f||0}},getEventTypeForStep:function(a){return this.state.steps[a-1]?this.state.steps[a-
1].eventType:""},moveHotspot:function(){var a=this.getHotspotForStep(this.state.overallStep);this.$elements.hotspot.css({top:a.top+"px",left:a.left+"px",width:a.width+"px",height:a.height+"px"});this.getEventTypeForStep(this.state.overallStep)==tryMe.CAPTURE_EVENT.TYPED&&(this.moveTypedHotspot(a),$("#typed-input-field").removeClass("hidden"))},moveTypedHotspot:function(a){0>a.width&&this.getCurrentStepObj().hideInput();$(tryMe.Typed.inputSelector,this.$container).css({width:a.width+"px",height:a.height+
"px"})},tryNext:function(a,b){return{then:function(b,d){a?b():d()}}},getCurrentStep:function(){return this.getCurrentStepFromOverallStep(this.state.overallStep)},getCurrentStepObj:function(){return 0==this.state.overallStep?!1:this.getStepObjById(this.state.overallStep)},getNextStep:function(){return this.state.overallStep+1},getNextStepObj:function(){return this.getStepObjById(this.getNextStep())},getStepObjById:function(a){return this.state.steps[a-1]},getCurrentSection:function(){return this.getCurrentSectionFromOverallStep(this.state.overallStep)},
getNumberOfSections:function(){return this.options.sections.length},overallStepIsLastStep:function(a){return a===this.state.steps.length},hideHintText:function(){this.$elements.hotspot.hasClass("tooltipstered")&&this.$elements.hotspot.tooltipster("destroy")},addFontInfoTo:function(a,b){null!=b&&b.useCustomTheme&&(null!=b.backgroundColor&&a.css({"background-color":this.getColorFromJavaColorString(b.backgroundColor)}),null!=b.textFillColor&&a.css({color:this.getColorFromJavaColorString(b.textFillColor)}),
null!=b.fontSize&&a.css({"font-size":this.getFontSizeFromJavaFontSize(b.fontSize)}),null!=b.fontType&&a.css({"font-family":b.fontType}))},getColorFromJavaColorString:function(a){return"#"+a.substring(a.indexOf("x")+1)},getFontSizeFromJavaFontSize:function(a){return a.split(" ").join("")},toggleRestartAnimation:function(a,b){this.$elements.infoScreen.find(".info-text").html(b||this.getCurrentStepObj().instructionalText);this.$elements.infoScreen.removeClass("modal-faded");this.$elements.infoScreen.find(".centered-element").show();
this.$elements.infoScreen.find(".info-restart").show();this.$elements.infoScreen.fadeIn(this.options.FADE_TIME).prop("disable",!1);a||setTimeout($.proxy(function(){this.closeInfoScreen()},this),this.options.FADE_TIME*this.options.FADE_MULTIPLIER)},closeInfoScreen:function(){this.$elements.infoScreen.addClass("modal-faded");this.$elements.infoScreen.fadeOut(this.options.FADE_TIME)},toggleContinueModal:function(){this.$elements.infoScreen.find(".info-restart").hide();this.$elements.continueScreen.fadeIn(this.options.FADE_TIME).prop("disable",
!1)},updateList:function(a){var b=this.getCurrentStepFromOverallStep(this.state.overallStep),c=this.getCurrentSectionFromOverallStep(this.state.overallStep),d=this,e=this.getCurrentStepObj(),f=e?e.hasHotspot():!1;this.state.prevEventType=this.state.currentEventType;e&&(this.state.currentEventType=e.eventType);this.$elements.sideContainer.find(".list-group .list-group-item").each(function(){var e=$(this).data("step-count"),g=$(this).data("section-count");g<c||g==c&&e<b?($(this).children(".try-me-done-overlay").show(),
d.toggleItemCircle($(this),"checkmark"),$(this).removeClass("active"),$(this).find(".continue-container").addClass("hidden"),$(this).addClass("disabled")):(g==c&&e==b?($(this).addClass("active"),$(this).removeClass("disabled"),(!f&&d.state.overallStep<d.state.steps.length||!f&&d.state.overallStep<=d.state.steps.length&&d.state.currentEventType!=tryMe.CAPTURE_EVENT.STOP)&&$(this).find(".continue-container").removeClass("hidden")):($(this).removeClass("active"),$(this).addClass("disabled")),$(this).children(".try-me-done-overlay").hide(),
d.state.overallStep==d.state.steps.length?d.toggleItemCircle($(this),"checkmark"):d.toggleItemCircle($(this),"number"),a&&a($(this)))});!f||f&&this.state.overallStep+1>this.state.steps.length?this.state.overallStep==this.state.steps.length&&this.state.currentEventType==tryMe.CAPTURE_EVENT.STOP||this.state.overallStep+1>this.state.steps.length?($(e).one(tryMe.EVENT.STEP_FINISHED,$.proxy(function(){this.toggleRestartAnimation(!1,e.getRestartText())},this)),f||d.state.currentEventType==tryMe.CAPTURE_EVENT.STOP||
d.state.completedSteps.includes(d.state.overallStep)||this.toggleContinueModal()):this.toggleContinueModal():(this.$elements.continueScreen.prop("disabled",!0).fadeOut(),this.$elements.infoScreen.prop("disabled",!0).fadeOut(this.options.FADE_TIME));0==this.state.overallStep||0==this.$elements.infoScreen.prop("disabled")?(this.$elements.hotspot.css("visibility","hidden"),this.$elements.hintButton.hide()):this.state.currentEventType==tryMe.CAPTURE_EVENT.TYPED?(this.$elements.hotspot.css("visibility",
"hidden"),this.toggleTypingTooltip(!0),null!=this.getCurrentStepObj().stringTyped&&this.$elements.hotspot.css("visibility",""),this.$elements.hintButton.prop("disabled",!1),this.$elements.hintButton.show()):(this.$elements.hotspot.css("visibility",""),this.toggleTypingTooltip(!1),this.$elements.hintButton.show(),this.$elements.hintButton.prop("disabled",!1));this.$elements.hotspot.removeClass("hotspotHint")},toggleItemCircle:function(a,b){a.find(".step-checkmark, .step-number").hide().filter(".step-"+
b).show()},showTooltip:function(a,b){b=b||{};if(b.content){a.hasClass("tooltipstered")&&a.tooltipster("destroy");var c=this.getToolTipPosition(a),d=0,e=!0,f=this,h=b.functionReady||function(){};delete b.functionReady;var g=b.functionAfter||function(){};delete b.functionAfter;"right"===c&&(d=this.$elements.carouselContainer.height()/2,e=!1);b=$.extend({content:"",position:c,maxWidth:Math.max(this.$elements.carousel.width()/2,250),functionPosition:function(a,b,c){c.coord.top/=f.options.scale();c.coord.left/=
f.options.scale();c.size.height/=f.options.scale();c.size.width/=f.options.scale();c.target/=f.options.scale();c.coord.top+=d;a=$(b.tooltip).find("img").get();for(var e=0;e<a.length;e++){var g=a[e];$(g).on("load",function(){g.naturalWidth>b.geo.available.document.right.width&&$(g).css("max-width",""+(b.geo.available.document.right.width-b.geo.available.document.right.width/100*5)+"px")})}return c},functionReady:function(a,b){f.openTooltip=$(b.tooltip);f.doTooltipForFullScreen();h.call(this,a,b)},
functionAfter:function(a){f.openTooltip=null;g.call(this,a)},trigger:"hover",arrow:e,interactive:!0,theme:this.options.TOOLTIP_THEME},b);var c={"overflow-y":"auto","word-break":"break-word","max-height":Math.max(this.$elements.carousel.height()/2,250)+"px"},e=!0,k,l;try{l=$(b.content)}catch(m){e=!1}e&&(k=l.find(".content"),e=k[0]?!0:!1);e?(k.css(c),b.content=l):b.content=$("\x3cdiv\x3e",{css:c}).append(b.content);b.content.find("h4").css("max-width",Math.max(this.$elements.carousel.width()/2,250)+
"px");a.tooltipster(b).tooltipster("show")}},showHintText:function(a){this.getHintTextForStep(a)&&this.showTooltip(this.$elements.hotspot,{content:this.getHintTextForStep(a)})},getToolTipPosition:function(a){a=this.$elements.hotspot.position();a.height=this.$elements.hotspot.height();a.width=this.$elements.hotspot.width();return 0>a.width?"right":(a.top+(a.top+a.height))/2>this.$elements.carouselContainer.height()/2?"top":"bottom"},getHintTextForStep:function(a){var b=this.state.steps[a-1].hintText;
this.getEventTypeForStep(a)!=tryMe.CAPTURE_EVENT.TYPED||b||(b=this.state.steps[a-1].instructionalText);return b},showTypedTextHint:function(a){a.currentStepValidated||($(tryMe.Typed.inputSelector,this.$container).val(""),$(tryMe.Typed.inputSelector,this.$container).trigger("focus"));$(tryMe.Typed.inputSelector,this.$container).addClass("inputHotSpotHint");var b=this;setTimeout(function(){$(tryMe.Typed.inputSelector,b.$container).removeClass("inputHotSpotHint")},4E3)},toggleTypingTooltip:function(a){if(a){var b=
this;null==this.getCurrentStepObj().stringTyped?(this.$elements.hotspot.attr("data-original-title","\x3cp\x3e"+this.getCurrentStepObj().instructionalText+"\x3c/p\x3e"+this.$elements.tooltipTemplate.prop("innerHTML")).tooltip({html:!0,trigger:"manual",container:this.$elements.carousel,placement:"auto bottom"}).tooltip("show"),this.$elements.carousel.find(".tooltip .btn-continue").on("click",function(){b.nextStep()})):$(tryMe.Typed.inputSelector,this.$container).trigger("focus")}else this.$elements.hotspot.tooltip("hide"),
this.$elements.carousel.find(".tooltip .btn-continue").off()},scrollToStep:function(){var a=this.$elements.sideContainer.find(this.sideContainerScrollParentSelector),b=this.$elements.sideContainer.find(".active"),b="auto"===a.css("overflow-y")?{scrollTop:(b[0]?b.position().top:0)-a.position().top+a.scrollTop()}:{scrollLeft:(b[0]?b.position().left:0)-a.position().left+a.scrollLeft()};a.stop();a.animate(b)},toggleRestartButton:function(){$restartBTN=this.$elements.carouselContainer.find(".try-me-restart-btn");
this.state.restartButtonEnabled?$restartBTN.removeClass("disabled"):$restartBTN.addClass("disabled")},toggleHintButton:function(){$hintButton=this.$elements.hintButton;this.state.hintButtonEnabled?$hintButton.removeClass("disabled"):$hintButton.addClass("disabled")},resizeSideContainer:function(){this.$elements.sideContainer.find(".panel").css("max-height",this.$elements.carouselContainer.height()+"px");this.moveHotspot()},positionDragOverlay:function(a,b){this.getScale();b=this.getHotspotForStep(b||
this.state.overallStep);this.$elements.dragOverlay.width(b.width);this.$elements.dragOverlay.height(b.height);a?(this.$elements.dragOverlay.css("left",a.pageX-this.$elements.carousel.offset().left-b.width/2),this.$elements.dragOverlay.css("top",a.pageY-this.$elements.carousel.offset().top-b.height/2)):(this.$elements.dragOverlay.css("left",b.left),this.$elements.dragOverlay.css("top",b.top))},resetDrag:function(a,b){this.state.dragging=!1;if(a)this.$elements.dragOverlay.fadeOut("fast");else this.$elements.dragOverlay[b?
"css":"animate"]({top:this.$elements.hotspot.css("top"),left:this.$elements.hotspot.css("left"),opacity:0})},getScale:function(){var a=this.getOverallStep?this.getOverallStep()-1:0;return captureProjectUtils.getScale(this.$elements,this.state.fullscreen,a)},xyInElement:function(a,b,c){c=c[0].getBoundingClientRect();return c.left<=a&&a<=c.right&&c.top+window.scrollY<=b&&b<=c.bottom+window.scrollY?!0:!1},getOverallStep:function(){return this.state.overallStep},goToStep:function(a){this.$elements.sideContainer.find(".list-group");
var b=$(a).closest("li").attr("data-step-count");a=$(a).closest("li").attr("data-section-count");b=parseInt(b,10);a=parseInt(a,10);b=this.getOverallStepFromSectionAndStep(a,b);~this.state.completedSteps.indexOf(b)&&b<=this.state.steps.length&&this.doStepChange(b,function(){this.state.overallStep==this.state.steps.length-1&&this.$elements.continueScreen.find(".info-continue").show()})},nextStep:function(){this.state.hintButtonEnabled=!0;this.toggleHintButton();this.doStepChange(this.getNextStep(),
function(){this.state.overallStep!=this.state.steps.length-1&&this.$elements.continueScreen.find(".info-continue").show();0>this.state.completedSteps.indexOf(this.state.overallStep)&&0!=this.state.overallStep&&this.state.completedSteps.push(this.state.overallStep);if(0==this.state.overAllStep)this.onEndReached()},this.state.currentEventType===tryMe.CAPTURE_EVENT.DRAG_FINISH)},prevStep:function(){this.state.currentEventType!==tryMe.CAPTURE_EVENT.DRAG_FINISH?this.doStepChange(this.state.overallStep-
1,void 0,!1):this.doStepChange(this.state.overallStep-1)},getNextStep:function(){return this.state.overallStep+1},doStepChange:function(a,b,c){this.hideHintText();this.state.restartButtonEnabled=1<this.state.overallStep;this.state.hintButtonEnabled=1<this.state.overallStep;this.toggleRestartButton();this.toggleHintButton();var d=0===this.state.overallStep,e=this.getCurrentStepObj(),f=this.getStepObjById(a);this.$elements.sideContainer.find(".list-group .continue-container").addClass("hidden");this.$elements.sideContainer.find(".active .arrow-hint.arrow-hint-active").removeClass("arrow-hint-active");
e&&e.finish();f&&(this.$elements.startScreen.fadeOut(this.options.FADE_TIME).find("button").prop("disabled",!0),this.$elements.carousel.carousel(Math.max(0,a-1)),this.state.overallStep=a);this.moveHotspot();(d||this.state.currentEventType!==tryMe.CAPTURE_EVENT.DRAG_FINISH||this.state.currentEventType===tryMe.CAPTURE_EVENT.DRAG_FINISH&&c)&&this.updateList();this.scrollToStep();if(f){var h=this;f.onInteraction(function(a,b){var c=this;h.tryNext(a,b).then(function(){h.doStepWillContiueAction(c)},function(){h.doStepNoContinueAction(c)})}).start()}b&&
b.apply(this);this.$container.trigger(tryMe.EVENT.STEP_CHANGED,this)},doStepWillContiueAction:function(a){if(a.onContinueAction)this[a.onContinueAction](a);a.onContinue()},doStepNoContinueAction:function(a){if(a.noContinueAction)this[a.noContinueAction](a);a.onNoContinue()},onEndReached:function(){this.$elements.startScreen.fadeIn(this.options.FADE_TIME).find("button").prop("disabled",!1)},flashTypedStepHint:function(){var a=this.$elements.sideContainer.find(".active");a.addClass("stepHint");setTimeout(function(){a.removeClass("stepHint")},
400)},flashHint:function(a){var b=this.$elements.sideContainer.find(".active");a&&this.$elements.hintButton.addClass("stepHint");b.addClass("stepHint");setTimeout($.proxy(function(){this.$elements.hintButton.removeClass("stepHint");b.removeClass("stepHint")},this),400)},flashContinue:function(){this.$elements.sideContainer.find(".active .arrow-hint").addClass("arrow-hint-active")},showTypedStepHint:function(a){this.showTypedTextHint(a)},showHint:function(a,b){a=a||this.state.overallStep;if(stepObj=
this.state.steps[a-1]){this.$elements.hintButton.prop("disabled",!0);var c=this.getEventTypeForStep(a+1);stepObj.eventType==tryMe.CAPTURE_EVENT.DRAG_START&&c==tryMe.CAPTURE_EVENT.DRAG_FINISH?(this.getScale(),c=this.getHotspotForStep(a+1),this.positionDragOverlay(null,a),this.$elements.dragOverlay.show(),this.$elements.dragOverlay.css("opacity",1),this.$elements.dragOverlay.stop(),this.$elements.dragOverlay.animate({left:c.left+c.width/2-this.$elements.hotspot.width()/2,top:c.top+c.height/2-this.$elements.hotspot.height()/
2},1E3,$.proxy(function(){this.$elements.dragOverlay.fadeOut("fast");this.$elements.hintButton.prop("disabled",!1)},this))):stepObj.eventType==tryMe.CAPTURE_EVENT.TYPED?this.showTypedStepHint(stepObj):0<this.$elements.hotspot.height()?this.$elements.hotspot.addClass("hotspotHint"):this.flashContinue();b||this.showHintText(a);this.$container.trigger(tryMe.EVENT.HINT,this)}},toggleFullscreen:function(){captureProjectUtils.toggleFullscreen(this.$container,this.$elements,this.getScale(),$.proxy(function(a){this.state.fullscreen=
a;this.state.fullscreen?(this.$elements.carouselContainer.addClass("capture-fullscreen-height"),this.$container.addClass("capture-fullscreen-overflow")):(this.$elements.carouselContainer.removeClass("capture-fullscreen-height"),this.$container.removeClass("capture-fullscreen-overflow"));this.doTooltipForFullScreen()},this))},doTooltipForFullScreen:function(){this.openTooltip&&this.openTooltip.appendTo(this.state.fullscreen?this.$elements.carousel:$("body"))},destroy:function(){$(window).off("resize."+
this.$container.attr("id"));this.$elements.carousel.off();this.$elements.hotspot.off();this.$elements.carousel.off();this.$elements.carousel.find("img").off();this.$elements.startScreen.find(".btn").off();this.$elements.continueScreen.find(".btn").off();this.$elements.hintButton.off();this.$elements=null;clearInterval(this.state.resizeInterval);clearInterval(this.state.assessTimer)},getStepFactory:function(){this.stepFactory||(this.stepFactory=new tryMe.StepFactory);return this.stepFactory}};
tryMe.StepFactory=function(){};
tryMe.StepFactory.prototype={getClassPath:function(a){switch(a.eventType){case tryMe.CAPTURE_EVENT.DRAG_START:a="DragStart";break;case tryMe.CAPTURE_EVENT.DRAG_FINISH:a="DragFinish";break;case tryMe.CAPTURE_EVENT.KEY_COMBO:case tryMe.CAPTURE_EVENT.SPECIAL_KEY:a="Step";break;case tryMe.CAPTURE_EVENT.TYPED:a="Typed";break;case tryMe.CAPTURE_EVENT.SELECT:a="Select";break;case tryMe.CAPTURE_EVENT.STOP:a="StopCapture";break;default:a="ClickStep"}return a},createStep:function(a,b,c){var d=this.getClassPath(a),
d=this.findClass(d);d||(d=tryMe.Step);return new d(a,b,c)},findClass:function(a){return tryMe[a]}};tryMe.Step=function(a,b,c){this.id=c;this.player=b;this.interactionHandler=function(){};this.subscribedElements=[];var d=this;$.each(a,function(b,c){d[b]=a[b]});return this};tryMe.Step.continueButtonSelector=".info-continue .btn-step-continue";
tryMe.Step.prototype={onContinueAction:"nextStep",start:function(){this.bindHandlers();this.hasHotspot()||this.setupNoHotspot();return this},finish:function(){this.removeHandlers();return this},onInteraction:function(a){this.interactionHandler=a;return this},interacted:function(a,b){return this.interactionHandler.call(this,a,b)},subscribe:function(a,b,c){a=a.split(" ").map(function(a){return a+".stepEvent"}).join(" ");if(b)this.player.$elements.carousel.on(a,b,c);else this.player.$elements.carousel.on(a,
c);this.subscribedElements.push(this.player.$elements.carousel)},removeHandlers:function(){for(var a=0;a<this.subscribedElements.length;a++)this.subscribedElements[a].off(".stepEvent")},hasHotspot:function(){return 0<parseInt(this.hotSpot.width,10)&&0<parseInt(this.hotSpot.height,10)},setupNoHotspot:function(a){var b=this,c=this.player.$elements.sideContainer.find(".row.active"),d=c.find(tryMe.Step.continueButtonSelector);d.on("click.stepEvent",function(a){a.stopPropagation();c.find(".arrow-hint").removeClass("arrow-hint-active");
b.interacted(!0,a)});a||this.subscribe("mousedown","",function(a){b.interacted(!1,a)});this.subscribedElements.push(d)},getRestartText:function(){return this.player.options.STRINGS.RESTART_TEXT},onContinue:function(){$(this).trigger(tryMe.EVENT.STEP_FINISHED)},bindHandlers:function(){},onNoContinue:function(){},hotspotResized:function(){}};tryMe.ClickStep=function(){tryMe.Step.apply(this,arguments);this.clicks=0};
tryMe.ClickStep.prototype=$.extend(Object.create(tryMe.Step.prototype),{bindHandlers:function(){var a=this,b=function(a){$(a).off("contextmenu touchend mouseup")},c=function(b){a.validateClickEvent(b,function(c){a.interacted(!0,b)},function(c){a.clicks==parseInt(c,10)&&c||(a.player.flashHint(!a.player.$elements.hintButton.prop("disabled")),a.interacted(!1,b))})};this.subscribe("mousedown touchstart",".targetHotspot",function(a){b(this);$(this).one("contextmenu",function(){b(this);c(a);return!1});
$(this).one("mouseup touchend",function(e){b(this);c(a);return!1});return!1});this.subscribe("mouseup touchstart","",function(b,c){c||(a.player.flashHint(!a.player.$elements.hintButton.prop("disabled")),clearTimeout(a.clickTimer),a.clicks=0)})},validateClickEventImmediate:function(a,b,c){this.validateClickEvent(a,b,c,!0)},validateClickEvent:function(a,b,c,d){var e=this,f=function(){c(this.clickCount);e.clicks==parseInt(this.clickCount,10)&&this.clickCount||(e.clicks=0)};this.convertToCaptureMouseButton(a).matches(this.mouseButton||
0)?(a.preventDefault(),a.stopPropagation(),this.clicks++,this.clicks!==parseInt(this.clickCount,10)&&this.clickCount?((1<this.clicks&&1<parseInt(this.clickCount,10)||!this.clickCount)&&clearTimeout(this.clickTimer),d?f():this.clickTimer=setTimeout(f,1500)):(this.clicks=0,b(this.clickCount),null!==this.clickTimer&&clearTimeout(this.clickTimer))):((1<this.clicks&&1<parseInt(this.clickCount,10)||!this.clickCount)&&clearTimeout(this.clickTimer),f())},convertToCaptureMouseButton:function(a){var b=a.button||
0,c=this;switch(b){case 0:b=[0,1];break;case 1:b=[3];break;default:b=[b]}return{matches:function(d){return~b.indexOf(d)||"touchstart"==a.type&&c.options.mobile}}}});tryMe.DragStart=function(){tryMe.Step.apply(this,arguments)};
tryMe.DragStart.prototype=$.extend(Object.create(tryMe.Step.prototype),{bindHandlers:function(){var a=this;this.subscribe("mousedown touchstart",".targetHotspot",function(b){a.event=b;a.interacted(!0,b);a.player.$elements.dragOverlay.stop()})},finish:function(){tryMe.Step.prototype.finish.call(this);this.event&&(this.player.positionDragOverlay(this.event),this.player.$elements.dragOverlay.show(),this.player.$elements.dragOverlay.css("opacity",1))}});
tryMe.DragFinish=function(){tryMe.Step.apply(this,arguments);this.pass=!1};
tryMe.DragFinish.prototype=$.extend(Object.create(tryMe.Step.prototype),{noContinueAction:"prevStep",bindHandlers:function(){var a=this;this.subscribe("mousemove touchmove","",function(b){"touchmove"==b.type&&(b=b.originalEvent.touches[0]);a.player.positionDragOverlay(b)});this.subscribe("mouseup touchend",".targetHotspot",function(b){a.pass=!0;if("touchend"==b.type){var c=b.originalEvent.changedTouches[0];a.pass=a.xyInElement(c.pageX,c.pageY,a.$elements.hotspot)}a.interacted(a.pass,b);b.stopPropagation();
b.preventDefault()});this.subscribe("mouseup touchend","",function(b){a.pass=!1;a.interacted(a.pass,b)})},showDragProxy:function(a){this.player.positionDragOverlay(a);this.player.$elements.dragOverlay.show();this.player.$elements.dragOverlay.css("opacity",1)},finish:function(){tryMe.Step.prototype.finish.call(this);this.player.resetDrag(this.pass)}});tryMe.Typed=function(){tryMe.Step.apply(this,arguments);this.currentStepValidated=this.typingTriggered=!1};tryMe.Typed.inputSelector=".targetHotspot input";
tryMe.Typed.prototype=$.extend(Object.create(tryMe.Step.prototype),{start:function(){tryMe.Step.prototype.start.call(this);this.renderInput();this.setInputType();this.player.$elements.hotspot.css({visibility:""});this.player.addFontInfoTo(this.input,this.fontInfo);this.input[0].focus()},renderInput:function(){this.player.$elements.hotspot.html("");this.input=$('\x3cinput type\x3d"text" class\x3d"form-control hidden" id\x3d"typed-input-field"\x3e').appendTo(this.player.$elements.hotspot)},setInputType:function(){this.password&&
this.input.attr("type","password");this.initialText&&this.input.val(this.initialText)},bindHandlers:function(){var a=this;this.subscribe("keydown",tryMe.Typed.inputSelector,function(b){~[tryMe.CONST.TAB_BUTTON,tryMe.CONST.ENTER_BUTTON].indexOf(b.keyCode)?(b.preventDefault(),a.interacted(b)):a.currentStepValidated=!1});this.subscribe("keyup",tryMe.Typed.inputSelector,function(b){b.preventDefault();a.typingTriggered=!0});this.subscribe("mouseup touchstart","",function(b,c){c||a.player.flashTypedStepHint()});
"MOUSE_MOVED"===this.reasonTypingEnded&&this.subscribe("mousemove touchmove","",function(b){if(a.typingTriggered)return a.interacted(b),a.typingTriggered=!1})},interacted:function(a,b){var c=this.nextStepStringValidation(),d=this.nextStepReasonTypedEndedValidation(a.keyCode),e=c&&d,c=$.proxy(function(){tryMe.Step.prototype.interacted.call(this,e,a)},this);!this.hasHotspot()&&"boolean"===typeof a&&b?tryMe.Step.prototype.interacted.call(this,a,b):e?this.doPassAnimation("MOUSE_MOVED"==this.reasonTypingEnded||
"CAPTURE_ENDED"==this.reasonTypingEnded,c):c()},doPassAnimation:function(a,b){a?($(tryMe.Typed.inputSelector,this.$container).prop("disabled",!0),setTimeout(function(){$(tryMe.Typed.inputSelector,self.$container).prop("disabled",!1);b()},1E3)):b()},nextStepStringValidation:function(){var a=this.input.val().replace(/^\s+|\s+$/g,"");return this.currentStepValidated=this.regularExpression&&this.regularExpression!==this.stringTyped?this.doRegexComparison(a):this.doTextComparison(a)},doRegexComparison:function(a){return a.match(new RegExp(this.regularExpression))?
!0:!1},doTextComparison:function(a){var b=this.caseSensitive?"variant":"accent";return this.compareStringLocale("A","a","base")?this.compareStringLocale(a,this.stringTyped,b):this.compareString(a,this.stringTyped,this.caseSensitive)},nextStepReasonTypedEndedValidation:function(a){return a==tryMe.CONST.ENTER_BUTTON&&"ENTER_PRESSED"==this.reasonTypingEnded||a==tryMe.CONST.TAB_BUTTON&&"TAB_PRESSED"==this.reasonTypingEnded||"MOUSE_MOVED"==this.reasonTypingEnded&&a!=tryMe.CONST.ENTER_BUTTON&&a!=tryMe.CONST.TAB_BUTTON||
"CAPTURE_ENDED"==this.reasonTypingEnded?!0:!1},compareStringLocale:function(a,b,c){return 0===a.localeCompare(b,void 0,{sensitivity:c})},compareString:function(a,b,c){return c?stringTyped===eventStringTyped:stringTyped.toUpperCase()===eventStringTyped.toUpperCase()},hideInput:function(){this.input&&(this.input.attr("placeholder","").val(""),this.input.hasClass("hidden")||this.input.addClass("hidden"))},hotspotResized:function(a,b){0>hotspot.width&&this.hideInput();a.css({width:b.width+"px",height:b.height+
"px"})},finish:function(){tryMe.Step.prototype.finish.call(this);this.hideInput()}});tryMe.StopCapture=function(){tryMe.Step.apply(this,arguments)};tryMe.StopCapture.prototype=$.extend(Object.create(tryMe.Step.prototype),{setupNoHotspot:function(){tryMe.Step.prototype.setupNoHotspot.call(this,!0);$(this).trigger(tryMe.EVENT.STEP_FINISHED)},getRestartText:function(){return this.instructionalText}});tryMe.Select=function(){tryMe.Step.apply(this,arguments);this.pass=!1;this.correctOption=0};
tryMe.Select.prototype=$.extend(Object.create(tryMe.Step.prototype),{start:function(){tryMe.Step.prototype.start.apply(this);this.renderSelect()},bindHandlers:function(){var a=this;this.subscribe("change",".targetHotspot select",function(b){a.pass=$(this).val()===a.correct;a.interacted(a.pass,b)})},renderSelect:function(a){a="\x3cselect\x3e";for(var b=0;b<this.options.length;b++)a+='\x3coption value\x3d"'+this.options[b]+'"'+(this.options[b]===this.initialSelection?"selected":"")+"\x3e"+this.options[b]+
"\x3c/option\x3e";this.player.$elements.hotspot.html(a+"\x3c/select\x3e");this.player.addFontInfoTo(this.player.$elements.hotspot.children().first(),this.fontInfo)},hotspotResized:function(a,b,c){a.find("select").css({transform:"scale("+c+")","transform-origin":"top left",width:1/c*b.width+"px",height:1/c*b.height+"px"})},finish:function(){this.player.$elements.hotspot.find("select").remove()}});